// ═══════════════════════════════════════════════════════════════════
// Vertical landing page data — extracted from app/*/page.tsx
// ═══════════════════════════════════════════════════════════════════

export interface GhostWorkItem {
  code: string
  label: string
  pain: string
  win: string
  hrs: string
}

export interface StudioType {
  id: string
  name: string
  note: string
}

export interface Stat {
  value: string
  label: string
}

export interface Testimonial {
  stat: string
  quote: string
  name: string
  biz: string
}

export interface ProcessStep {
  n: string
  title: string
  body: string
  note: string
}

export interface VerticalConfig {
  slug: string
  name: string           // display name like "Dental Practices"
  ogTitle: string
  proSection: string     // e.g. "DENTAL & ORAL HEALTH"
  heroBeforeBr: string   // text before <br /> in h1
  heroAfterBr: string    // text after <br /> in h1 (simple or with <span>)
  heroBody: string
  ctaText: string
  ghostWorkTitle: string
  ghostWorkBody: string
  ghostWorkTotal: string
  section3Title: string
  section4Title: string
  resultSection: string
  tools: string[]
  ghostWork: GhostWorkItem[]
  studioTypes: StudioType[]
  stats: Stat[]
  testimonials: Testimonial[]
  processSteps: ProcessStep[]
  defaultIndustry: string
  serviceSchemaName: string
  serviceSchemaDesc: string
}

export const VERTICALS: Record<string, VerticalConfig> = {
  dental: {
    slug: 'dental',
    name: 'Dental Practices',
    ogTitle: 'Stop Running Your Dental Practice on Ghost Work — eevolvv',
    proSection: 'DENTAL &amp; ORAL HEALTH',
    heroBeforeBr: 'Dental practices recover',
    heroAfterBr: '<span style={{ color: \'var(--accent)\' }}>$36K+/year</span> in missed recalls and no-shows.',
    heroBody: 'Recalls, no-shows, insurance pre-auth, intake forms — done by AI agents, deployed in 14 days. Most practices recover 15–20 hours/week and $2K–$4K/month in lost revenue.',
    ctaText: 'GET FREE PRACTICE AUDIT →',
    ghostWorkTitle: 'Ghost work hiding in every dental practice.',
    ghostWorkBody: 'These aren\'t inefficiencies you can hustle through. They\'re structural drains that compound every month — losing you patients, revenue, and the hours you should be spending on care.',
    ghostWorkTotal: '14–23 hours per week recovered across a typical dental practice.',
    section3Title: 'Every practice type. One AI engine.',
    section4Title: 'Free audit. Custom report. Automations built for you.',
    resultSection: '§ 05 · RESULTS',
    tools: ['Dentrix', 'Eaglesoft', 'Open Dental', 'Carestream', 'Weave', 'NexHealth', 'Zocdoc', 'Availity', 'Stripe'],
    ghostWork: [
      { code: 'G-01', label: 'Recall Campaigns', pain: 'Manually calling patients 6 months after their last visit — most never get called at all', win: 'Automated recall sequence sends texts and emails at the right interval, recovering 15–25% of lapsed patients', hrs: '3–5 hrs/wk' },
      { code: 'G-02', label: 'No-Shows', pain: 'Patients forgetting appointments costs $200–$300 per slot in lost revenue', win: 'Automated reminder sequence (7-day, 48-hr, 2-hr) cuts no-shows by 30–50%', hrs: '2–4 hrs/wk' },
      { code: 'G-03', label: 'New Patient Intake', pain: 'Paper forms and manual data entry for every new patient — slow and error-prone', win: 'Automated digital intake sent before the visit; data flows directly into your system', hrs: '2–3 hrs/wk' },
      { code: 'G-04', label: 'Insurance Pre-Auth', pain: 'Chasing insurance approvals one by one before every procedure', win: 'Automated pre-auth tracking with alerts when approval is needed or delayed', hrs: '3–4 hrs/wk' },
      { code: 'G-05', label: 'Online Reviews', pain: 'Great patient outcomes with no system to turn them into Google reviews', win: 'Automated post-visit review request at the right moment in the patient journey', hrs: '1–2 hrs/wk' },
      { code: 'G-06', label: 'Billing Reconciliation', pain: 'Manually matching EOBs to claims, then chasing outstanding balances', win: 'Automated billing error detection and AR follow-up sequences', hrs: '3–5 hrs/wk' },
    ],
    studioTypes: [
      { id: 'D-01', name: 'General Dentistry', note: 'Hygiene scheduling, recall, new patient intake' },
      { id: 'D-02', name: 'Cosmetic Dentistry', note: 'Consult funnels, treatment plan follow-up, financing' },
      { id: 'D-03', name: 'Orthodontics', note: 'Treatment milestones, retainer reminders, referral programs' },
      { id: 'D-04', name: 'Pediatric Dentistry', note: 'Parent communication, appointment reminders, school forms' },
      { id: 'D-05', name: 'Oral Surgery', note: 'Pre-op and post-op sequences, consent forms, referral tracking' },
      { id: 'D-06', name: 'Periodontics', note: 'Maintenance scheduling, recall, insurance coordination' },
      { id: 'D-07', name: 'Dental Groups', note: 'Multi-location reporting, centralized scheduling, staff comms' },
      { id: 'D-08', name: 'Dental Spas', note: 'Membership programs, upsell sequences, review campaigns' },
    ],
    stats: [
      { value: '30–50%', label: 'reduction in no-shows with automated reminder sequences' },
      { value: '6–10 hrs', label: 'saved per week on front-desk admin and scheduling' },
      { value: '15–25%', label: 'lapsed patients recovered via automated recall campaigns' },
      { value: '40–60%', label: 'faster new patient intake with digital pre-visit forms' },
    ],
    testimonials: [
      { stat: '18 hrs/wk recovered', quote: 'The recall system alone recovered more in month one than the entire year\'s subscription costs. It runs completely on autopilot.', name: 'Dr. Sarah M.', biz: 'General Dentistry — Phoenix, AZ' },
      { stat: '+41% trial conversion', quote: 'Our no-show rate went from 18% to 7% in six weeks. That\'s real revenue we were leaving on the table every single day.', name: 'James K.', biz: 'Orthodontic Practice — Denver, CO' },
      { stat: '1 day/mo → zero', quote: 'New patient intake used to take 20 minutes of manual work. Now the form goes out automatically and data lands in Dentrix before we even say hello.', name: 'Dr. Priya S.', biz: 'Cosmetic Dentistry — Austin, TX' },
    ],
    processSteps: [
      { n: '01', title: 'AI Diagnostic', body: '10-minute AI conversation maps your operation — workflows, tools, pain points, team size, revenue. No forms. Just a conversation.', note: 'Free · No signup' },
      { n: '02', title: 'Evolution Report', body: 'Your custom report quantifies exactly how many hours you\'re losing, which automations will recover them first, and a 90-day build roadmap.', note: 'Delivered instantly' },
      { n: '03', title: 'We Build It', body: 'Choose your tier. We build every automation from the report — custom agents, integrations, and workflows — within days, not months.', note: 'Agent One from $499/mo' },
    ],
    defaultIndustry: 'Medical / Healthcare',
    serviceSchemaName: 'AI Automation for Dental Practices',
    serviceSchemaDesc: 'Dental offices recover 15-20 hrs/week by automating recalls, no-shows, and patient intake.',
  },

  medspa: {
    slug: 'medspa',
    name: 'Med Spas & Aesthetic Clinics',
    ogTitle: 'Stop Running Your Med Spa on Ghost Work — eevolvv',
    proSection: 'MED SPA &amp; AESTHETICS',
    heroBeforeBr: 'Your med spa is running on',
    heroAfterBr: '<span style={{ color: \'var(--accent)\' }}>ghost work.</span>',
    heroBody: 'Appointment no-shows, consent form chasing, treatment recall gaps, membership lapsing — med spas lose 15–20 hours every week to tasks that should be automated. We find them, name them, and build the fix.',
    ctaText: 'GET FREE SPA AUDIT →',
    ghostWorkTitle: 'Ghost work hiding in every med spa.',
    ghostWorkBody: 'These aren\'t inefficiencies you can hustle through. They\'re structural drains that compound every month — losing you clients, revenue, and the hours you should be spending on treatments.',
    ghostWorkTotal: '13–21 hours per week recovered across a typical med spa.',
    section3Title: 'Every aesthetic practice. One AI engine.',
    section4Title: 'Free audit. Custom report. Automations built for you.',
    resultSection: '§ 05 · RESULTS',
    tools: ['Boulevard', 'Vagaro', 'Mindbody', 'Zenoti', 'Jane', 'Stripe', 'Mailchimp', 'Twilio', 'Calendly'],
    ghostWork: [
      { code: 'G-01', label: 'Appointment No-Shows', pain: 'A Botox slot going unfilled costs $150–$500 in lost revenue — and manual reminders don\'t scale', win: 'Automated 72-hr, 24-hr, and 2-hr reminder sequence cuts no-shows by 35–50%', hrs: '2–4 hrs/wk' },
      { code: 'G-02', label: 'Consent Form Collection', pain: 'Emailing consent forms, chasing signatures, printing and filing manually for every visit', win: 'Digital consent sent automatically before the appointment, signed and stored — no paper, no chasing', hrs: '3–4 hrs/wk' },
      { code: 'G-03', label: 'Treatment Recalls', pain: 'Clients who need a touch-up in 3 months — most never get a timely follow-up', win: 'Automated recall sequences timed to each treatment type: filler, Botox, laser, IV, etc.', hrs: '3–5 hrs/wk' },
      { code: 'G-04', label: 'Membership Renewals', pain: 'Members lapsing because no one remembered to send the renewal conversation', win: 'Automated renewal sequence starting 60 days out — membership retention improves 20–30%', hrs: '2–3 hrs/wk' },
      { code: 'G-05', label: 'Review Collection', pain: 'Transformative results with no system to turn satisfied clients into Google reviews', win: 'Post-treatment review ask at peak satisfaction moment — 25–35% more reviews generated', hrs: '1–2 hrs/wk' },
      { code: 'G-06', label: 'Rebooking', pain: 'Clients leaving with great results but no next appointment booked', win: 'Automated rebooking nudge sequence 2–4 weeks after treatment, with before/after portfolio prompts', hrs: '2–3 hrs/wk' },
    ],
    studioTypes: [
      { id: 'MS-01', name: 'Medical Spas', note: 'Full-service booking, membership, and recall automation' },
      { id: 'MS-02', name: 'Botox & Filler Clinics', note: 'Treatment recalls, consent flows, rebooking sequences' },
      { id: 'MS-03', name: 'Laser Hair Removal', note: 'Package tracking, session reminders, completion upsell' },
      { id: 'MS-04', name: 'IV Therapy Lounges', note: 'Membership programs, wellness sequences, booking automation' },
      { id: 'MS-05', name: 'Body Contouring', note: 'Treatment series tracking, progress check-ins, referral programs' },
      { id: 'MS-06', name: 'Cosmetic Injectors', note: 'Solo practice automation, booking, consent, and follow-up' },
      { id: 'MS-07', name: 'Aesthetics Clinics', note: 'Multi-provider scheduling, package management, loyalty' },
      { id: 'MS-08', name: 'Wellness Centers', note: 'Holistic service sequencing, member communication, upsell flows' },
    ],
    stats: [
      { value: '35–50%', label: 'fewer no-shows with automated appointment reminders' },
      { value: '5–8 hrs', label: 'saved per week on front-desk admin and consent workflows' },
      { value: '20–30%', label: 'more membership renewals with automated retention sequences' },
      { value: '25–35%', label: 'more Google reviews with post-treatment solicitation' },
    ],
    testimonials: [
      { stat: '$12K/mo saved', quote: 'Our no-show rate was destroying our most popular injector\'s schedule. The automated reminder sequence cut it from 22% to 8% in the first month.', name: 'Maya R.', biz: 'Medical Spa — Miami, FL' },
      { stat: '16 hrs/wk saved', quote: 'Consent forms alone took 3 hours a day — emailing, chasing, filing. Now clients sign on their phone before they even walk in.', name: 'Dr. Alicia V.', biz: 'Aesthetics — Austin, TX' },
      { stat: '+28% retention', quote: 'Our membership renewal rate jumped 28% in 90 days. The 60-day reminder sequence catches people before they even think about canceling.', name: 'Chris T.', biz: 'Wellness Center — Denver, CO' },
    ],
    processSteps: [
      { n: '01', title: 'AI Diagnostic', body: '10-minute AI conversation maps your operation — workflows, tools, pain points, team size, revenue. No forms. Just a conversation.', note: 'Free · No signup' },
      { n: '02', title: 'Evolution Report', body: 'Your custom report quantifies exactly how many hours you\'re losing, which automations will recover them first, and a 90-day build roadmap.', note: 'Delivered instantly' },
      { n: '03', title: 'We Build It', body: 'Choose your tier. We build every automation from the report — custom agents, integrations, and workflows — within days, not months.', note: 'Agent One from $499/mo' },
    ],
    defaultIndustry: 'Medical / Healthcare',
    serviceSchemaName: 'AI Automation for Med Spas & Aesthetic Clinics',
    serviceSchemaDesc: 'Med spas and aesthetic clinics recover 15-20 hrs/week by automating bookings, recalls, and membership renewals.',
  },

  chiro: {
    slug: 'chiro',
    name: 'Chiropractic & PT Practices',
    ogTitle: 'Stop Running Your Chiropractic Practice on Ghost Work — eevolvv',
    proSection: 'CHIROPRACTIC &amp; PHYSICAL THERAPY',
    heroBeforeBr: 'Your chiropractic practice is running on',
    heroAfterBr: '<span style={{ color: \'var(--accent)\' }}>ghost work.</span>',
    heroBody: 'Appointment no-shows, lapsed patient recall, insurance verification, manual intake — chiro practices lose 15–20 hours every week to tasks that should be automated. We find them, name them, and build the fix.',
    ctaText: 'GET FREE PRACTICE AUDIT →',
    ghostWorkTitle: 'Ghost work hiding in every practice.',
    ghostWorkBody: 'These aren\'t inefficiencies you can hustle through. They\'re structural drains that compound every month — losing you patients, revenue, and the hours you should be spending on adjustments.',
    ghostWorkTotal: '13–23 hours per week recovered across a typical practice.',
    section3Title: 'Every practice type. One AI engine.',
    section4Title: 'Free audit. Custom report. Automations built for you.',
    resultSection: '§ 05 · RESULTS',
    tools: ['ChiroTouch', 'Jane', 'Mindbody', 'TherapyNotes', 'WebPT', 'Stripe', 'Twilio', 'Zocdoc', 'Calendly'],
    ghostWork: [
      { code: 'G-01', label: 'Appointment No-Shows', pain: 'An adjustment slot going unfilled costs $80–$150 in lost revenue — manual reminder calls don\'t scale', win: 'Automated 48-hr and 2-hr reminder sequence cuts no-shows by 30–50%', hrs: '2–4 hrs/wk' },
      { code: 'G-02', label: 'Lapsed Patient Recall', pain: 'Patients who stopped treatment 3–6 months ago — most never get a meaningful follow-up', win: 'Automated recall campaign with personalized care check-in recovers 15–25% of lapsed patients', hrs: '3–5 hrs/wk' },
      { code: 'G-03', label: 'New Patient Intake', pain: 'Paper intake forms, manual data entry, insurance verification done separately for every new patient', win: 'Automated digital intake before the visit; insurance verification triggered automatically', hrs: '2–4 hrs/wk' },
      { code: 'G-04', label: 'Insurance Verification', pain: 'Manually calling to verify benefits before every new patient — hours per week', win: 'Automated insurance verification tracking with alerts for issues before the appointment', hrs: '3–5 hrs/wk' },
      { code: 'G-05', label: 'Treatment Plan Follow-Up', pain: 'Patients dropping off mid-plan because no proactive outreach reminds them of their progress', win: 'Automated treatment milestone check-ins reinforce adherence and outcomes', hrs: '2–3 hrs/wk' },
      { code: 'G-06', label: 'Review Collection', pain: 'Patients getting great results but no system to turn relief into Google reviews', win: 'Automated post-treatment review request at peak satisfaction — reviews increase 3–4x', hrs: '1–2 hrs/wk' },
    ],
    studioTypes: [
      { id: 'CH-01', name: 'Chiropractic Clinics', note: 'Adjustment reminders, recall campaigns, insurance coordination' },
      { id: 'CH-02', name: 'Physical Therapy', note: 'Exercise adherence tracking, milestone check-ins, referral tracking' },
      { id: 'CH-03', name: 'Sports Medicine', note: 'Athlete progress sequences, return-to-play protocols, review collection' },
      { id: 'CH-04', name: 'Massage Therapy', note: 'Session reminders, package renewal, referral programs' },
      { id: 'CH-05', name: 'Acupuncture', note: 'Treatment series tracking, wellness campaigns, rebooking automation' },
      { id: 'CH-06', name: 'Holistic Wellness', note: 'Membership management, workshop funnels, email sequences' },
      { id: 'CH-07', name: 'Pain Management', note: 'Outcome tracking, case coordination, patient education sequences' },
      { id: 'CH-08', name: 'Multi-Specialty Clinics', note: 'Cross-referral automation, unified scheduling, revenue reporting' },
    ],
    stats: [
      { value: '30–50%', label: 'fewer no-shows with automated appointment reminders' },
      { value: '15–25%', label: 'lapsed patients recovered via automated recall campaigns' },
      { value: '60%', label: 'faster new patient intake with digital pre-visit forms' },
      { value: '40–60%', label: 'less insurance admin time with automated verification tracking' },
    ],
    testimonials: [
      { stat: '40% fewer no-shows', quote: 'Our no-show rate dropped from 26% to 15% in 4 weeks. The automated reminders are a game-changer — patients even thank us for them.', name: 'Dr. Mike R.', biz: 'Chiropractic — Dallas, TX' },
      { stat: '18 hrs/wk recovered', quote: 'The recall system brought back 23 lapsed patients in month one. That\'s $4,600 in reappointment revenue we would have never seen.', name: 'Dr. Lisa C.', biz: 'PT Clinic — Portland, OR' },
      { stat: '60% faster intake', quote: 'Digital intake forms eliminated our front-desk bottleneck. New patients complete everything on their phone before walking in.', name: 'Dr. Eric W.', biz: 'Sports Medicine — Boulder, CO' },
    ],
    processSteps: [
      { n: '01', title: 'AI Diagnostic', body: '10-minute AI conversation maps your operation — workflows, tools, pain points, team size, revenue. No forms. Just a conversation.', note: 'Free · No signup' },
      { n: '02', title: 'Evolution Report', body: 'Your custom report quantifies exactly how many hours you\'re losing, which automations will recover them first, and a 90-day build roadmap.', note: 'Delivered instantly' },
      { n: '03', title: 'We Build It', body: 'Choose your tier. We build every automation from the report — custom agents, integrations, and workflows — within days, not months.', note: 'Agent One from $499/mo' },
    ],
    defaultIndustry: 'Medical / Healthcare',
    serviceSchemaName: 'AI Automation for Chiropractic & Physical Therapy Practices',
    serviceSchemaDesc: 'Chiropractic offices and PT practices recover 15-20 hrs/week by automating recalls, intake, and patient retention.',
  },

  fitness: {
    slug: 'fitness',
    name: 'Gyms & Fitness Studios',
    ogTitle: 'Stop Running Your Gym on Ghost Work — eevolvv',
    proSection: 'FITNESS &amp; WELLNESS',
    heroBeforeBr: 'Gyms cut churn by <span style={{ color: \'var(--accent)\' }}>30%</span>',
    heroAfterBr: 'and recover 15–25 hrs/week of admin time.',
    heroBody: 'Gyms and fitness studios lose 15–25 hours and dozens of members every month to manual admin. We find the ghost work, name it, and build the fix — so you can grow instead of grind.',
    ctaText: 'GET FREE GYM AUDIT →',
    ghostWorkTitle: 'Ghost work hiding in every gym.',
    ghostWorkBody: 'These aren\'t inefficiencies you can hustle through. They\'re structural drains that compound every month — losing you members, revenue, and the hours you should be spending on coaching.',
    ghostWorkTotal: '16–26 hours per week recovered across a typical gym.',
    section3Title: 'Every fitness type. One AI engine.',
    section4Title: 'Free audit. Custom report. Automations built for you.',
    resultSection: '§ 05 · RESULTS',
    tools: ['Mindbody', 'Zenoti', 'Wodify', 'PushPress', 'ClubReady', 'Stripe', 'Mailchimp', 'Twilio', 'ClassPass'],
    ghostWork: [
      { code: 'G-01', label: 'Member Churn', pain: 'Manually tracking who stopped showing up — usually too late to save them', win: 'Automated early-warning system flags at-risk members at the first missed class', hrs: '4–6 hrs/wk' },
      { code: 'G-02', label: 'New Member Onboarding', pain: 'Paper waivers, manual payment setup, tour follow-ups falling through the cracks', win: 'Automated digital waiver + payment setup + 14-day welcome sequence for every new member', hrs: '3–5 hrs/wk' },
      { code: 'G-03', label: 'Class Scheduling Changes', pain: 'Members texting to cancel or switch classes — manually tracking every change', win: 'Self-serve scheduling with automated waitlist management and change notifications', hrs: '2–4 hrs/wk' },
      { code: 'G-04', label: 'Billing & Collections', pain: 'Failed payments, manual retries, awkward conversations about overdue dues', win: 'Automated dunning sequence with retries, reminders, and payment link re-sends', hrs: '3–4 hrs/wk' },
      { code: 'G-05', label: 'Review Collection', pain: 'Great coaches, great results — zero Google reviews because nobody remembers to ask', win: 'Automated post-workout review request triggers at peak endorphin moment', hrs: '1–2 hrs/wk' },
      { code: 'G-06', label: 'Referral Activation', pain: 'Members would refer their friends — you just haven\'t asked them at the right time', win: 'Automated referral nudges after milestone achievements or member anniversaries', hrs: '2–3 hrs/wk' },
    ],
    studioTypes: [
      { id: 'F-01', name: 'CrossFit Boxes', note: 'WOD scheduling, challenge campaigns, member retention' },
      { id: 'F-02', name: 'BJJ & MMA Academies', note: 'Belt tracking, event announcements, comp registration' },
      { id: 'F-03', name: 'Yoga & Pilates Studios', note: 'Class booking, workshop funnels, membership management' },
      { id: 'F-04', name: 'Boutique Fitness', note: 'Session packages, rebooking flows, referral programs' },
      { id: 'F-05', name: 'Personal Training', note: 'Client check-ins, program delivery, progress milestones' },
      { id: 'F-06', name: 'Dance Studios', note: 'Recital coordination, costume orders, parent communications' },
      { id: 'F-07', name: 'Swim Schools', note: 'Class scheduling, weather closures, progress reporting' },
      { id: 'F-08', name: 'Multi-Sport Facilities', note: 'Unified booking, member dashboards, revenue reporting' },
    ],
    stats: [
      { value: '25–35%', label: 'better member retention with automated re-engagement sequences' },
      { value: '15–25 hrs', label: 'saved per week on admin, billing, and scheduling' },
      { value: '3–5x', label: 'more Google reviews with automated post-workout solicitation' },
      { value: '40%', label: 'faster new member onboarding with digital intake workflows' },
    ],
    testimonials: [
      { stat: '30% lower churn', quote: 'The early-warning system flagged 12 at-risk members in our first week. We saved 8 of them with a simple check-in call.', name: 'Jake P.', biz: 'CrossFit Box — Austin, TX' },
      { stat: '22 hrs/wk saved', quote: 'Onboarding used to take 45 minutes per member with paper forms and manual payment setup. Now it\'s 5 minutes and they\'re in the system before they leave.', name: 'Sarah L.', biz: 'Yoga Studio — San Diego, CA' },
      { stat: '4x review volume', quote: 'We went from 2 reviews a month to 18 in the first month of automated post-workout asks. It\'s our best lead source now.', name: 'Marcus J.', biz: 'BJJ Academy — Denver, CO' },
    ],
    processSteps: [
      { n: '01', title: 'AI Diagnostic', body: '10-minute AI conversation maps your operation — workflows, tools, pain points, team size, revenue. No forms. Just a conversation.', note: 'Free · No signup' },
      { n: '02', title: 'Evolution Report', body: 'Your custom report quantifies exactly how many hours you\'re losing, which automations will recover them first, and a 90-day build roadmap.', note: 'Delivered instantly' },
      { n: '03', title: 'We Build It', body: 'Choose your tier. We build every automation from the report — custom agents, integrations, and workflows — within days, not months.', note: 'Agent One from $499/mo' },
    ],
    defaultIndustry: 'Fitness & Wellness',
    serviceSchemaName: 'AI Automation for Gyms & Fitness Studios',
    serviceSchemaDesc: 'Gyms and fitness studios recover 15-25 hrs/week and cut member churn by 25-35% with AI automation.',
  },

  restaurant: {
    slug: 'restaurant',
    name: 'Restaurants',
    ogTitle: 'Stop Running Your Restaurant on Ghost Work — eevolvv',
    proSection: 'RESTAURANTS &amp; FOOD SERVICE',
    heroBeforeBr: 'Restaurants recapture',
    heroAfterBr: '<span style={{ color: \'var(--accent)\' }}>$2K–$5K/month</span> in no-shows, reorders, and scheduling waste.',
    heroBody: 'No-shows, staff scheduling chaos, manual inventory tracking, missed review opportunities — restaurants lose 15–25 hours every week to tasks that should be automated. We find them, name them, and build the fix.',
    ctaText: 'GET FREE RESTAURANT AUDIT →',
    ghostWorkTitle: 'Ghost work hiding in every restaurant.',
    ghostWorkBody: 'These aren\'t inefficiencies you can hustle through. They\'re structural drains that compound every month — losing you tables, revenue, and the hours you should be spending on food.',
    ghostWorkTotal: '13–22 hours per week recovered across a typical restaurant.',
    section3Title: 'Every restaurant type. One AI engine.',
    section4Title: 'Free audit. Custom report. Automations built for you.',
    resultSection: '§ 05 · RESULTS',
    tools: ['Toast', 'Square', 'Clover', 'OpenTable', 'Resy', '7shifts', 'Stripe', 'Slack', 'Mailchimp'],
    ghostWork: [
      { code: 'G-01', label: 'No-Shows', pain: 'Tables sitting empty because a guest forgot their reservation — no automatic reminder went out', win: 'Automated 24-hr and 2-hr confirmation sequence cuts no-shows by 30–40%', hrs: '2–4 hrs/wk' },
      { code: 'G-02', label: 'Staff Scheduling', pain: 'Spreadsheets, group texts, and manual shift swaps — every week it\'s a nightmare', win: 'Automated schedule publishing with shift swap requests and availability matching', hrs: '3–5 hrs/wk' },
      { code: 'G-03', label: 'Inventory Alerts', pain: 'Running out of a key ingredient mid-service because nobody tracked par levels', win: 'Automated low-stock alerts based on par levels and usage velocity', hrs: '2–3 hrs/wk' },
      { code: 'G-04', label: 'Order & Takeout Management', pain: 'Juggling phone orders, online orders, and third-party delivery — manually entering each one', win: 'Unified order dashboard with automated routing to POS and kitchen display', hrs: '4–6 hrs/wk' },
      { code: 'G-05', label: 'Review Collection', pain: 'Great food, terrible review volume — nobody has a system to ask satisfied diners', win: 'Automated post-meal review request via text or email at the right moment', hrs: '1–2 hrs/wk' },
      { code: 'G-06', label: 'Private Event Inquiries', pain: 'Event leads coming in and getting lost because there\'s no structured follow-up process', win: 'Automated event inquiry response and follow-up sequence for every lead', hrs: '2–3 hrs/wk' },
    ],
    studioTypes: [
      { id: 'R-01', name: 'Full-Service Restaurants', note: 'Reservation management, no-show reduction, review collection' },
      { id: 'R-02', name: 'Quick Service / Fast Casual', note: 'Order management, inventory alerts, staffing optimization' },
      { id: 'R-03', name: 'Cafes & Coffee Shops', note: 'Loyalty programs, catering inquiries, event booking' },
      { id: 'R-04', name: 'Food Trucks & Pop-Ups', note: 'Location announcements, schedule automation, inventory tracking' },
      { id: 'R-05', name: 'Pizzerias', note: 'Order funnel automation, delivery follow-up, loyalty sequences' },
      { id: 'R-06', name: 'Bakeries', note: 'Pre-order management, wholesale ordering, seasonal campaigns' },
      { id: 'R-07', name: 'Bars & Breweries', note: 'Event scheduling, guest list management, taproom announcements' },
      { id: 'R-08', name: 'Catering Companies', note: 'Menu delivery, proposal automation, event coordination' },
    ],
    stats: [
      { value: '30–40%', label: 'fewer no-shows with automated reservation reminders' },
      { value: '4–6 hrs', label: 'saved per week on staff scheduling with shift automation' },
      { value: '25–35%', label: 'more reviews with post-meal automated solicitation' },
      { value: '40–60%', label: 'faster event lead response with automated inquiry handling' },
    ],
    testimonials: [
      { stat: '35% fewer no-shows', quote: 'We were losing $3K/month to no-shows. The automated SMS reminders cut that by more than half in week one.', name: 'Marco V.', biz: 'Italian Restaurant — Chicago, IL' },
      { stat: '5 hrs/wk saved', quote: 'Scheduling was taking me 5 hours every Sunday. Now it publishes automatically and shift swaps go through the app.', name: 'Jenny K.', biz: 'Brewpub — Portland, OR' },
      { stat: '3x review count', quote: 'We went from 3 reviews a month to 11. The automated ask hits tables right after dessert — perfect timing.', name: 'David H.', biz: 'Fine Dining — Dallas, TX' },
    ],
    processSteps: [
      { n: '01', title: 'AI Diagnostic', body: '10-minute AI conversation maps your operation — workflows, tools, pain points, team size, revenue. No forms. Just a conversation.', note: 'Free · No signup' },
      { n: '02', title: 'Evolution Report', body: 'Your custom report quantifies exactly how many hours you\'re losing, which automations will recover them first, and a 90-day build roadmap.', note: 'Delivered instantly' },
      { n: '03', title: 'We Build It', body: 'Choose your tier. We build every automation from the report — custom agents, integrations, and workflows — within days, not months.', note: 'Agent One from $499/mo' },
    ],
    defaultIndustry: 'Restaurant / Food Service',
    serviceSchemaName: 'AI Automation for Restaurants',
    serviceSchemaDesc: 'Restaurants recover 15-25 hrs/week by automating no-shows, scheduling, and inventory.',
  },

  salon: {
    slug: 'salon',
    name: 'Salons & Barbershops',
    ogTitle: 'Stop Running Your Salon on Ghost Work — eevolvv',
    proSection: 'SALONS &amp; BARBERSHOPS',
    heroBeforeBr: 'Your salon is running on',
    heroAfterBr: '<span style={{ color: \'var(--accent)\' }}>ghost work.</span>',
    heroBody: 'No-shows, rebooking gaps, retail upsell, manual review chasing — salons and barbershops lose 10–15 hours every week to tasks that should be automated. We find them, name them, and build the fix.',
    ctaText: 'GET FREE SALON AUDIT →',
    ghostWorkTitle: 'Ghost work hiding in every salon.',
    ghostWorkBody: 'These aren\'t inefficiencies you can hustle through. They\'re structural drains that compound every month — losing you chairs, revenue, and the hours you should be spending on clients.',
    ghostWorkTotal: '12–19 hours per week recovered across a typical salon.',
    section3Title: 'Every salon type. One AI engine.',
    section4Title: 'Free audit. Custom report. Automations built for you.',
    resultSection: '§ 05 · RESULTS',
    tools: ['Booksy', 'Vagaro', 'Square Appointments', 'StyleSeat', 'Mindbody', 'Stripe', 'Mailchimp', 'Twilio', 'Calendly'],
    ghostWork: [
      { code: 'G-01', label: 'No-Shows', pain: 'A stylist sitting idle for an hour costs $80–$200 in lost chair revenue — manual reminder calls don\'t scale', win: 'Automated 48-hr and 2-hr reminder sequence cuts no-shows by 35–50%', hrs: '2–4 hrs/wk' },
      { code: 'G-02', label: 'Rebooking Automation', pain: 'Client leaves with great results but no next appointment booked — you hope they remember to call', win: 'Automated rebooking nudge at checkout with one-tap scheduling and product upsell', hrs: '2–3 hrs/wk' },
      { code: 'G-03', label: 'Retail Upsell', pain: 'Selling products happens only when the stylist remembers to mention it — inconsistent at best', win: 'Automated post-visit product recommendation and purchase link based on services rendered', hrs: '1–2 hrs/wk' },
      { code: 'G-04', label: 'Gift Card Sales', pain: 'No system to remind clients that holidays, birthdays, and anniversaries are perfect gift card moments', win: 'Automated gift card campaigns timed to occasions and client visit history', hrs: '1–2 hrs/wk' },
      { code: 'G-05', label: 'Review Collection', pain: 'Amazing transformations with no system to turn them into Google reviews', win: 'Automated post-visit review request with style photo prompt at peak satisfaction', hrs: '1–2 hrs/wk' },
      { code: 'G-06', label: 'Product Reorder Alerts', pain: 'Running out of popular retail products because nobody tracks inventory usage vs. sales', win: 'Automated low-stock alerts for retail products based on historical velocity', hrs: '1–2 hrs/wk' },
    ],
    studioTypes: [
      { id: 'S-01', name: 'Hair Salons', note: 'Booking, rebooking, retail upsell, and review automation' },
      { id: 'S-02', name: 'Barbershops', note: 'Walk-in management, appointment scheduling, loyalty programs' },
      { id: 'S-03', name: 'Nail Salons', note: 'Service menu automation, gift card campaigns, membership plans' },
      { id: 'S-04', name: 'Day Spas', note: 'Package tracking, treatment series, member communications' },
      { id: 'S-05', name: 'Lash & Brow Studios', note: 'Fill-in scheduling, retention reminders, rebooking flows' },
      { id: 'S-06', name: 'Tattoo Shops', note: 'Consult booking, design approval, deposit management' },
      { id: 'S-07', name: 'Tanning Salons', note: 'Membership management, session tracking, promo campaigns' },
      { id: 'S-08', name: 'Mobile Hair & Beauty', note: 'Route scheduling, availability windows, booking automation' },
    ],
    stats: [
      { value: '35–50%', label: 'fewer no-shows with automated appointment reminders' },
      { value: '40%', label: 'more client rebookings with automated checkout nudges' },
      { value: '3–5x', label: 'more reviews with post-visit automated solicitation' },
      { value: '20–30%', label: 'increase in retail product sales with automated upsell' },
    ],
    testimonials: [
      { stat: '50% fewer no-shows', quote: 'I used to spend my Sunday evenings calling clients to confirm Monday appointments. Now it happens automatically and my no-show rate dropped in half.', name: 'Stella R.', biz: 'Hair Salon — Brooklyn, NY' },
      { stat: '$2K/mo retail upsell', quote: 'The post-visit product recommendations generate $500/week in add-on sales. Clients love the convenience of ordering directly.', name: 'Trey M.', biz: 'Barbershop — Atlanta, GA' },
      { stat: '5x more reviews', quote: 'We went from 1 Google review a week to 5. The photo prompt after a big transformation is genius — clients love showing off.', name: 'Nina Q.', biz: 'Lash Studio — Austin, TX' },
    ],
    processSteps: [
      { n: '01', title: 'AI Diagnostic', body: '10-minute AI conversation maps your operation — workflows, tools, pain points, team size, revenue. No forms. Just a conversation.', note: 'Free · No signup' },
      { n: '02', title: 'Evolution Report', body: 'Your custom report quantifies exactly how many hours you\'re losing, which automations will recover them first, and a 90-day build roadmap.', note: 'Delivered instantly' },
      { n: '03', title: 'We Build It', body: 'Choose your tier. We build every automation from the report — custom agents, integrations, and workflows — within days, not months.', note: 'Agent One from $499/mo' },
    ],
    defaultIndustry: 'Salon / Beauty',
    serviceSchemaName: 'AI Automation for Salons & Barbershops',
    serviceSchemaDesc: 'Salons and barbershops recover 10-15 hrs/week by automating no-shows, rebooking, and retail upsell.',
  },

  cleaning: {
    slug: 'cleaning',
    name: 'Cleaning & Home Service Businesses',
    ogTitle: 'Stop Running Your Cleaning Business on Ghost Work — eevolvv',
    proSection: 'CLEANING &amp; HOME SERVICES',
    heroBeforeBr: 'Your cleaning business is running on',
    heroAfterBr: '<span style={{ color: \'var(--accent)\' }}>ghost work.</span>',
    heroBody: 'Booking chaos, manual invoicing, last-minute cancellations, no-show cleaners, review chasing — cleaning businesses lose 15–20 hours every week to tasks that should be automated. We find them, name them, and build the fix.',
    ctaText: 'GET FREE BUSINESS AUDIT →',
    ghostWorkTitle: 'Ghost work hiding in every cleaning business.',
    ghostWorkBody: 'These aren\'t inefficiencies you can hustle through. They\'re structural drains that compound every month — losing you contracts, revenue, and the hours you should be spending on clients.',
    ghostWorkTotal: '13–24 hours per week recovered across a typical cleaning business.',
    section3Title: 'Every service type. One AI engine.',
    section4Title: 'Free audit. Custom report. Automations built for you.',
    resultSection: '§ 05 · RESULTS',
    tools: ['Housecall Pro', 'Jobber', 'ServiceTitan', 'Stripe', 'QuickBooks', 'Mailchimp', 'Twilio', 'Slack', 'Calendly'],
    ghostWork: [
      { code: 'G-01', label: 'Booking & Scheduling', pain: 'Back-and-forth texts to find a time that works, then manually blocking the calendar', win: 'Automated booking with available slots shown instantly and calendar sync', hrs: '3–5 hrs/wk' },
      { code: 'G-02', label: 'Invoicing & Payment', pain: 'Creating invoices one by one, chasing payments, reconciling bank deposits', win: 'Automated invoice generation + payment link + dunning sequence', hrs: '3–4 hrs/wk' },
      { code: 'G-03', label: 'Cancellation & Rebook', pain: 'Client cancels — now you scramble to fill the slot and follow up to rebook them', win: 'Automated cancellation handling + rebook nudge + slot notification to waitlist', hrs: '2–3 hrs/wk' },
      { code: 'G-04', label: 'Recurring Service Reminders', pain: 'Manually calling bi-weekly clients to remind them their cleaning is tomorrow', win: 'Automated pre-service reminders and post-service satisfaction check-ins', hrs: '2–3 hrs/wk' },
      { code: 'G-05', label: 'Review Collection', pain: 'Great cleanings with no system to turn satisfied clients into Google reviews', win: 'Automated post-service review request delivers 3–4x more reviews', hrs: '1–2 hrs/wk' },
      { code: 'G-06', label: 'Supply & Inventory', pain: 'Running out of cleaning supplies mid-week because nobody tracks usage', win: 'Automated low-stock alerts and reorder triggers based on service volume', hrs: '1–2 hrs/wk' },
    ],
    studioTypes: [
      { id: 'C-01', name: 'Residential Cleaning', note: 'Recurring scheduling, invoicing, and client communication' },
      { id: 'C-02', name: 'Commercial Cleaning', note: 'Contract management, crew coordination, compliance reporting' },
      { id: 'C-03', name: 'Carpet & Upholstery', note: 'Job tracking, follow-up sequences, seasonal campaigns' },
      { id: 'C-04', name: 'Window Cleaning', note: 'Weather-dependent scheduling, route optimization, estimate automation' },
      { id: 'C-05', name: 'Pressure Washing', note: 'Before/after portfolio, seasonal packages, referral programs' },
      { id: 'C-06', name: 'Junk Removal', note: 'Quote automation, scheduling, payment collection' },
      { id: 'C-07', name: 'Pest Control', note: 'Treatment reminders, seasonal follow-up, customer education' },
      { id: 'C-08', name: 'Landscaping / Lawn Care', note: 'Seasonal service calendars, weather alerts, automated invoicing' },
    ],
    stats: [
      { value: '40–60%', label: 'faster booking with automated scheduling and slot selection' },
      { value: '$2K–$4K/mo', label: 'fewer lost hours from no-shows with automated reminders' },
      { value: '3–4x', label: 'more reviews with post-service automated solicitation' },
      { value: '50%', label: 'faster payment collection with automated invoicing' },
    ],
    testimonials: [
      { stat: '5 hrs/wk saved', quote: 'I was spending 5 hours a week on scheduling texts. Now clients book their own slots and I get a notification. That\'s an entire workday back every week.', name: 'Maria L.', biz: 'Residential Cleaning — Phoenix, AZ' },
      { stat: '3x review volume', quote: 'We went from 5 reviews a month to 16. The post-clean text goes out right after we leave and the response rate is incredible.', name: 'Tony D.', biz: 'Commercial Cleaning — Chicago, IL' },
      { stat: '$3K recovered/mo', quote: 'Our no-show rate dropped from 20% to 8%. The automated reminders work — clients appreciate not forgetting their appointment.', name: 'Rosa M.', biz: 'Carpet Cleaning — Denver, CO' },
    ],
    processSteps: [
      { n: '01', title: 'AI Diagnostic', body: '10-minute AI conversation maps your operation — workflows, tools, pain points, team size, revenue. No forms. Just a conversation.', note: 'Free · No signup' },
      { n: '02', title: 'Evolution Report', body: 'Your custom report quantifies exactly how many hours you\'re losing, which automations will recover them first, and a 90-day build roadmap.', note: 'Delivered instantly' },
      { n: '03', title: 'We Build It', body: 'Choose your tier. We build every automation from the report — custom agents, integrations, and workflows — within days, not months.', note: 'Agent One from $499/mo' },
    ],
    defaultIndustry: 'Home Services',
    serviceSchemaName: 'AI Automation for Cleaning & Home Service Businesses',
    serviceSchemaDesc: 'Cleaning businesses recover 15-20 hrs/week by automating scheduling, invoicing, and client retention.',
  },

  'auto-shop': {
    slug: 'auto-shop',
    name: 'Auto Repair Shops',
    ogTitle: 'Stop Running Your Auto Shop on Ghost Work — eevolvv',
    proSection: 'AUTO REPAIR &amp; SERVICE',
    heroBeforeBr: 'Your auto shop is running on',
    heroAfterBr: '<span style={{ color: \'var(--accent)\' }}>ghost work.</span>',
    heroBody: 'Appointment no-shows, declined service follow-up, manual review chasing, slow estimate response — auto shops lose 10–20 hours every week to tasks that should be automated. We find them, name them, and build the fix.',
    ctaText: 'GET FREE SHOP AUDIT →',
    ghostWorkTitle: 'Ghost work hiding in every auto shop.',
    ghostWorkBody: 'These aren\'t inefficiencies you can hustle through. They\'re structural drains that compound every month — losing you bays, revenue, and the hours you should be spending under the hood.',
    ghostWorkTotal: '9–16 hours per week recovered across a typical auto shop.',
    section3Title: 'Every shop type. One AI engine.',
    section4Title: 'Free audit. Custom report. Automations built for you.',
    resultSection: '§ 05 · RESULTS',
    tools: ['ShopMonkey', 'Tekmetric', 'AutoLeap', 'Fullbay', 'Mitchell 1', 'Stripe', 'Twilio', 'QuickBooks', 'Slack'],
    ghostWork: [
      { code: 'G-01', label: 'Appointment No-Shows', pain: 'A bay sitting empty for 2 hours because a customer forgot to show — no reminder went out', win: 'Automated 48-hr and 2-hr reminder sequence cuts no-shows by 40–60%', hrs: '2–3 hrs/wk' },
      { code: 'G-02', label: 'Declined Service Follow-Up', pain: 'Customer declines a repair today — you have no system to follow up in 30 days when they\'ve thought it over', win: 'Automated declined service campaign: follow-up at 30, 60, and 90 days closes 25–40% of declined work', hrs: '2–4 hrs/wk' },
      { code: 'G-03', label: 'Service Completion Notification', pain: 'Customer calls to ask if their car is ready — they have no visibility into progress', win: 'Automated inspection-complete and pickup-ready notifications via text — inbound calls drop 50%', hrs: '1–2 hrs/wk' },
      { code: 'G-04', label: 'Seasonal Campaigns', pain: 'Missing the spring tire swap and winter prep revenue because no campaign went out', win: 'Automated seasonal service campaigns timed to local weather patterns and vehicle service history', hrs: '2–3 hrs/wk' },
      { code: 'G-05', label: 'Review Collection', pain: 'Great work, almost no Google reviews because nobody remembers to ask', win: 'Automated post-pickup review request at the right moment — 25–35% more reviews generated', hrs: '1–2 hrs/wk' },
      { code: 'G-06', label: 'Maintenance Reminders', pain: 'Customers coming back only when something breaks, not for preventive service', win: 'Automated vehicle maintenance reminders based on mileage and service history intervals', hrs: '1–2 hrs/wk' },
    ],
    studioTypes: [
      { id: 'A-01', name: 'Auto Repair Shops', note: 'Appointment reminders, declined service follow-up, review automation' },
      { id: 'A-02', name: 'Tire Centers', note: 'Seasonal campaigns, installation scheduling, alignment upsell' },
      { id: 'A-03', name: 'Body Shops', note: 'Estimate follow-up, insurance coordination, completion notifications' },
      { id: 'A-04', name: 'Transmission Shops', note: 'Diagnostic completion alerts, cost approval workflows, follow-up' },
      { id: 'A-05', name: 'Quick Lube', note: 'Mileage-based reminders, cross-sell sequences, loyalty programs' },
      { id: 'A-06', name: 'Custom / Performance Shops', note: 'Project milestone updates, parts order alerts, client communication' },
      { id: 'A-07', name: 'Dealership Service', note: 'Recall campaigns, loyalty service packages, appointment flows' },
      { id: 'A-08', name: 'Mobile Mechanics', note: 'Route optimization, booking automation, payment collection' },
    ],
    stats: [
      { value: '40–60%', label: 'fewer appointment no-shows with automated reminders' },
      { value: '25–40%', label: 'more declined services closed with follow-up automation' },
      { value: '25–35%', label: 'more Google reviews with post-service solicitation' },
      { value: '3–5 hrs', label: 'saved per week on manual admin and status calls' },
    ],
    testimonials: [
      { stat: '40% fewer no-shows', quote: 'We were losing $2K/month to empty bays. The automated SMS reminders cut no-shows by nearly half and our bays stay full.', name: 'Mike S.', biz: 'Auto Repair — Dallas, TX' },
      { stat: '30% more work closed', quote: 'The declined service follow-up brought back 30% of customers who originally said no. That\'s $4K in recovered work in 90 days.', name: 'Tony R.', biz: 'Tire Center — Chicago, IL' },
      { stat: '3x review volume', quote: 'We went from 2 reviews a month to 8. The text goes out right after they pick up their car — perfect timing.', name: 'Anna K.', biz: 'Body Shop — Phoenix, AZ' },
    ],
    processSteps: [
      { n: '01', title: 'AI Diagnostic', body: '10-minute AI conversation maps your operation — workflows, tools, pain points, team size, revenue. No forms. Just a conversation.', note: 'Free · No signup' },
      { n: '02', title: 'Evolution Report', body: 'Your custom report quantifies exactly how many hours you\'re losing, which automations will recover them first, and a 90-day build roadmap.', note: 'Delivered instantly' },
      { n: '03', title: 'We Build It', body: 'Choose your tier. We build every automation from the report — custom agents, integrations, and workflows — within days, not months.', note: 'Agent One from $499/mo' },
    ],
    defaultIndustry: 'Auto Repair',
    serviceSchemaName: 'AI Automation for Auto Repair Shops',
    serviceSchemaDesc: 'Auto repair shops recover 10-20 hrs/week by automating appointments, declined service follow-up, and reviews.',
  },

  childcare: {
    slug: 'childcare',
    name: 'Childcare Centers & Daycares',
    ogTitle: 'Stop Running Your Childcare Center on Ghost Work — eevolvv',
    proSection: 'CHILDCARE &amp; EARLY EDUCATION',
    heroBeforeBr: 'Your childcare center is running on',
    heroAfterBr: '<span style={{ color: \'var(--accent)\' }}>ghost work.</span>',
    heroBody: 'Enrollment paperwork, payment chasing, staff scheduling, parent communication — childcare centers lose 15–20 hours every week to tasks that should be automated. We find them, name them, and build the fix.',
    ctaText: 'GET FREE CENTER AUDIT →',
    ghostWorkTitle: 'Ghost work hiding in every childcare center.',
    ghostWorkBody: 'These aren\'t inefficiencies you can hustle through. They\'re structural drains that compound every month — losing you families, revenue, and the hours you should be spending with children.',
    ghostWorkTotal: '14–22 hours per week recovered across a typical center.',
    section3Title: 'Every center type. One AI engine.',
    section4Title: 'Free audit. Custom report. Automations built for you.',
    resultSection: '§ 05 · RESULTS',
    tools: ['BrightWheel', 'Procare', 'Kinderlime', 'HiMama', 'Tadpoles', 'Stripe', 'QuickBooks', 'Twilio', 'Mailchimp'],
    ghostWork: [
      { code: 'G-01', label: 'Enrollment Applications', pain: 'Paper forms, manual follow-up, and back-and-forth to get families fully enrolled', win: 'Automated enrollment sequence with digital forms, payment setup, and welcome materials', hrs: '3–5 hrs/wk' },
      { code: 'G-02', label: 'Payment Collection', pain: 'Chasing tuition payments manually, tracking who\'s late, sending reminders one by one', win: 'Automated tuition billing with payment links, late reminders, and dunning sequences', hrs: '3–4 hrs/wk' },
      { code: 'G-03', label: 'Staff Scheduling', pain: 'Spreadsheets and group texts to cover shifts, track PTO, and manage ratios', win: 'Automated scheduling with ratio compliance, shift swap, and time-off requests', hrs: '2–4 hrs/wk' },
      { code: 'G-04', label: 'Daily Reports to Parents', pain: 'Manually writing each family a daily summary of their child\'s activities', win: 'Automated daily report templates with photo upload and milestone tracking', hrs: '3–5 hrs/wk' },
      { code: 'G-05', label: 'Waitlist Management', pain: 'Families inquiring and getting lost — no structured follow-up when a spot opens', win: 'Automated waitlist with inquiry follow-up and immediate notification when space available', hrs: '2–3 hrs/wk' },
      { code: 'G-06', label: 'Emergency Communication', pain: 'Closing for weather or illness — manually calling every family', win: 'Automated emergency broadcast via text and email with read confirmation tracking', hrs: '1–2 hrs/wk' },
    ],
    studioTypes: [
      { id: 'CC-01', name: 'Daycare Centers', note: 'Enrollment, payment, daily reports, and parent communication' },
      { id: 'CC-02', name: 'Preschools', note: 'Registration automation, progress reports, event coordination' },
      { id: 'CC-03', name: 'Montessori Schools', note: 'Portfolio tracking, parent conferences scheduling, milestones' },
      { id: 'CC-04', name: 'After-School Programs', note: 'Enrollment management, attendance tracking, pick-up coordination' },
      { id: 'CC-05', name: 'Nannies & Au Pairs', note: 'Schedule management, daily logs, emergency contact workflows' },
      { id: 'CC-06', name: 'In-Home Daycares', note: 'Booking, payment collection, state compliance documentation' },
      { id: 'CC-07', name: 'Summer Camps', note: 'Registration funnels, medical forms, daily parent updates' },
      { id: 'CC-08', name: 'Early Intervention Centers', note: 'Session scheduling, progress tracking, insurance billing' },
    ],
    stats: [
      { value: '40–60%', label: 'faster enrollment with automated digital application workflows' },
      { value: '50%', label: 'faster payment collection with automated billing and reminders' },
      { value: '5–8 hrs', label: 'saved per week on admin, scheduling, and daily reports' },
      { value: '30–50%', label: 'fewer inbound parent calls with automated daily updates' },
    ],
    testimonials: [
      { stat: '50% faster enrollment', quote: 'Our enrollment process went from 3 weeks of back-and-forth to 4 days. Families fill out everything on their phone and the payment is set up before their tour.', name: 'Angela P.', biz: 'Preschool — Austin, TX' },
      { stat: '8 hrs/wk saved', quote: 'Daily reports used to take 3 hours every afternoon. Now parents get photos and updates automatically and they love it.', name: 'Maria T.', biz: 'Daycare Center — Denver, CO' },
      { stat: '$4K recovered/mo', quote: 'Our payment collection rate went from 78% to 95%. The automated reminders handle the awkward conversations for us.', name: 'Jason L.', biz: 'Childcare Network — Dallas, TX' },
    ],
    processSteps: [
      { n: '01', title: 'AI Diagnostic', body: '10-minute AI conversation maps your operation — workflows, tools, pain points, team size, revenue. No forms. Just a conversation.', note: 'Free · No signup' },
      { n: '02', title: 'Evolution Report', body: 'Your custom report quantifies exactly how many hours you\'re losing, which automations will recover them first, and a 90-day build roadmap.', note: 'Delivered instantly' },
      { n: '03', title: 'We Build It', body: 'Choose your tier. We build every automation from the report — custom agents, integrations, and workflows — within days, not months.', note: 'Agent One from $499/mo' },
    ],
    defaultIndustry: 'Childcare / Education',
    serviceSchemaName: 'AI Automation for Childcare Centers & Daycares',
    serviceSchemaDesc: 'Childcare centers recover 15-20 hrs/week by automating enrollment, payment, and parent communication.',
  },

  contractors: {
    slug: 'contractors',
    name: 'Contractors & Trades',
    ogTitle: 'Stop Running Your Contracting Business on Ghost Work — eevolvv',
    proSection: 'CONTRACTORS &amp; TRADES',
    heroBeforeBr: 'Your contracting business is running on',
    heroAfterBr: '<span style={{ color: \'var(--accent)\' }}>ghost work.</span>',
    heroBody: 'Quote generation, scheduling, job site coordination, invoicing, lien management — contractors and trades lose 20–30 hours every week to tasks that should be automated. We find them, name them, and build the fix.',
    ctaText: 'GET FREE CONTRACTOR AUDIT →',
    ghostWorkTitle: 'Ghost work hiding in every contracting business.',
    ghostWorkBody: 'These aren\'t inefficiencies you can hustle through. They\'re structural drains that compound every month — losing you jobs, revenue, and the hours you should be spending on site.',
    ghostWorkTotal: '18–30 hours per week recovered across a typical contracting business.',
    section3Title: 'Every trade. One AI engine.',
    section4Title: 'Free audit. Custom report. Automations built for you.',
    resultSection: '§ 05 · RESULTS',
    tools: ['Jobber', 'Housecall Pro', 'ServiceTitan', 'BuilderTrend', 'Procore', 'Stripe', 'QuickBooks', 'Twilio', 'Slack'],
    ghostWork: [
      { code: 'G-01', label: 'Quote Generation', pain: 'Creating custom estimates from scratch every time — same line items, different customer name', win: 'Automated quote builder with template-based generation and one-click adjustments', hrs: '4–6 hrs/wk' },
      { code: 'G-02', label: 'Job Scheduling', pain: 'Phone tag with customers to find available slots, then manually dispatching crews', win: 'Automated scheduling with slot selection and crew assignment based on skills and location', hrs: '3–5 hrs/wk' },
      { code: 'G-03', label: 'Field Communication', pain: 'Office not knowing crew progress — jobs stalling because nobody communicated changes', win: 'Automated job stage notifications with photo updates and change order alerts', hrs: '3–4 hrs/wk' },
      { code: 'G-04', label: 'Invoicing & Payment', pain: 'Creating invoices after every job, then chasing checks and reconciling payments', win: 'Automated invoice generation on job completion + payment link + dunning sequence', hrs: '4–5 hrs/wk' },
      { code: 'G-05', label: 'Lien Waiver & Compliance', pain: 'Manually tracking lien waivers, insurance certs, and license renewals', win: 'Automated document requests and compliance deadline alerts for every job', hrs: '2–3 hrs/wk' },
      { code: 'G-06', label: 'Review Collection', pain: 'Quality work with no system to turn satisfied clients into Google reviews', win: 'Automated post-completion review request increases review volume 3–4x', hrs: '1–2 hrs/wk' },
    ],
    studioTypes: [
      { id: 'H-01', name: 'HVAC', note: 'Seasonal maintenance reminders, quote automation, dispatching' },
      { id: 'H-02', name: 'Plumbing', note: 'Emergency dispatch, service follow-up, maintenance plans' },
      { id: 'H-03', name: 'Electrical', note: 'Permit tracking, inspection scheduling, job stage updates' },
      { id: 'H-04', name: 'Roofing', note: 'Storm lead response, estimate funnels, insurance coordination' },
      { id: 'H-05', name: 'General Contractors', note: 'Subcontractor coordination, project milestones, change orders' },
      { id: 'H-06', name: 'Landscaping', note: 'Recurring service scheduling, weather alerts, seasonal campaigns' },
      { id: 'H-07', name: 'Painting', note: 'Estimate automation, crew scheduling, completion follow-up' },
      { id: 'H-08', name: 'Remodeling', note: 'Project timeline automation, client approvals, material tracking' },
    ],
    stats: [
      { value: '40–60%', label: 'faster quote turnaround with template-based automation' },
      { value: '$5K–$8K/mo', label: 'recovered revenue from faster invoicing and payment follow-up' },
      { value: '50%', label: 'fewer missed jobs with automated scheduling and dispatch' },
      { value: '4x', label: 'more reviews with post-completion automated solicitation' },
    ],
    testimonials: [
      { stat: '40% faster quotes', quote: 'I used to spend 2 hours on every estimate. Now I punch in the numbers and the system generates it with the correct markup and line items.', name: 'Rick M.', biz: 'HVAC — Phoenix, AZ' },
      { stat: '$6K/mo recovered', quote: 'We were leaving money on the table with slow invoicing. Now invoices go out automatically when the job closes and payment comes within days.', name: 'Tom H.', biz: 'Plumbing — Denver, CO' },
      { stat: '4x review volume', quote: 'We went from 3 reviews a month to 14. The post-job text goes out right after final payment and clients are happy to share.', name: 'Danielle R.', biz: 'Remodeling — Austin, TX' },
    ],
    processSteps: [
      { n: '01', title: 'AI Diagnostic', body: '10-minute AI conversation maps your operation — workflows, tools, pain points, team size, revenue. No forms. Just a conversation.', note: 'Free · No signup' },
      { n: '02', title: 'Evolution Report', body: 'Your custom report quantifies exactly how many hours you\'re losing, which automations will recover them first, and a 90-day build roadmap.', note: 'Delivered instantly' },
      { n: '03', title: 'We Build It', body: 'Choose your tier. We build every automation from the report — custom agents, integrations, and workflows — within days, not months.', note: 'Agent One from $499/mo' },
    ],
    defaultIndustry: 'Home Services',
    serviceSchemaName: 'AI Automation for Contractors & Trades',
    serviceSchemaDesc: 'HVAC, plumbing, roofing, and general contractors recover 20-30 hrs/week by automating quotes, scheduling, and invoicing.',
  },

  ecommerce: {
    slug: 'ecommerce',
    name: 'E-commerce & Online Retail',
    ogTitle: 'Stop Running Your Store on Ghost Work — eevolvv',
    proSection: 'E-COMMERCE &amp; RETAIL',
    heroBeforeBr: 'Your store is running on',
    heroAfterBr: '<span style={{ color: \'var(--accent)\' }}>ghost work.</span>',
    heroBody: 'Abandoned cart recovery, inventory tracking, customer support, review generation, email flows — your store loses 15–20 hours every week to tasks that should be automated. We find them, name them, and build the fix.',
    ctaText: 'GET FREE STORE AUDIT →',
    ghostWorkTitle: 'Ghost work hiding in every store.',
    ghostWorkBody: 'These aren\'t inefficiencies you can hustle through. They\'re structural drains that compound every month — losing you sales, margin, and the hours you should be spending on product.',
    ghostWorkTotal: '14–23 hours per week recovered across a typical e-commerce store.',
    section3Title: 'Every store type. One AI engine.',
    section4Title: 'Free audit. Custom report. Automations built for you.',
    resultSection: '§ 05 · RESULTS',
    tools: ['Shopify', 'WooCommerce', 'BigCommerce', 'Klaviyo', 'Gorgias', 'Stripe', 'QuickBooks', 'Slack', 'ShipStation'],
    ghostWork: [
      { code: 'G-01', label: 'Abandoned Cart', pain: '30–40% of carts are abandoned and most stores send one generic reminder — if any', win: 'Automated 3-step abandoned cart sequence (1-hr, 24-hr, 72-hr) recovers 10–15% of lost revenue', hrs: '3–5 hrs/wk' },
      { code: 'G-02', label: 'Inventory Sync', pain: 'Stock goes out of sync between warehouse, storefront, and marketplaces — leading to overselling', win: 'Automated multi-channel inventory reconciliation with low-stock alerts and reorder triggers', hrs: '3–5 hrs/wk' },
      { code: 'G-03', label: 'Customer Support Triage', pain: 'Same questions coming in daily — tracking, returns, sizing — answered manually every time', win: 'Automated FAQ triage with AI responses for common queries; humans handle exceptions only', hrs: '4–6 hrs/wk' },
      { code: 'G-04', label: 'Order Fulfillment Status', pain: 'Customers emailing "where\'s my order?" because they don\'t get proactive updates', win: 'Automated order lifecycle notifications: confirmation, shipped, out-for-delivery, delivered', hrs: '2–3 hrs/wk' },
      { code: 'G-05', label: 'Review & UGC Collection', pain: 'Great products but almost no reviews — spending manual effort asking for them', win: 'Automated post-delivery review request timed to estimated arrival + photo incentive', hrs: '2–3 hrs/wk' },
      { code: 'G-06', label: 'Back-in-Stock Alerts', pain: 'Customers wanting to buy sold-out items — no system to notify them when inventory arrives', win: 'Automated back-in-stock notification sequence with personalized restock alerts', hrs: '1–2 hrs/wk' },
    ],
    studioTypes: [
      { id: 'E-01', name: 'DTC Brands', note: 'Post-purchase flows, retention automation, UGC collection' },
      { id: 'E-02', name: 'Multi-Channel Sellers', note: 'Unified inventory, order routing, cross-platform reporting' },
      { id: 'E-03', name: 'Subscription Boxes', note: 'Renewal sequences, churn reduction, upgrade funnels' },
      { id: 'E-04', name: 'Marketplace Sellers', note: 'FBA automation, listing management, repricing alerts' },
      { id: 'E-05', name: 'Print on Demand', note: 'Order automation, supplier coordination, fulfillment tracking' },
      { id: 'E-06', name: 'Wholesale / B2B', note: 'Minimum order automation, account management, reorder alerts' },
      { id: 'E-07', name: 'Handmade / Craft', note: 'Pre-order management, custom order workflows, waitlist automation' },
      { id: 'E-08', name: 'Digital Products', note: 'Delivery automation, license management, upsell sequences' },
    ],
    stats: [
      { value: '10–15%', label: 'abandoned cart revenue recovered with automated sequences' },
      { value: '40–60%', label: 'fewer inbound support tickets with automated FAQ triage' },
      { value: '3–5 hrs', label: 'saved per week on inventory reconciliation and stock alerts' },
      { value: '3–4x', label: 'more product reviews with post-delivery automated solicitation' },
    ],
    testimonials: [
      { stat: '12% cart recovery', quote: 'Our abandoned cart recovery went from a single email to a 3-step sequence that recovers 12% of what we were losing. That\'s $8K/month in recovered revenue.', name: 'Henry L.', biz: 'DTC Brand — Austin, TX' },
      { stat: '6 hrs/wk saved', quote: 'Customer support was drowning in "where\'s my order" questions. The automated order status flow cut inbound tickets by 60%.', name: 'Priya S.', biz: 'Fashion E-commerce — NYC, NY' },
      { stat: '4x review volume', quote: 'We went from 5 reviews a month to 22. The post-delivery text goes out right when they\'ve unboxed — perfect timing.', name: 'Marcus W.', biz: 'Home Goods — Portland, OR' },
    ],
    processSteps: [
      { n: '01', title: 'AI Diagnostic', body: '10-minute AI conversation maps your operation — workflows, tools, pain points, team size, revenue. No forms. Just a conversation.', note: 'Free · No signup' },
      { n: '02', title: 'Evolution Report', body: 'Your custom report quantifies exactly how many hours you\'re losing, which automations will recover them first, and a 90-day build roadmap.', note: 'Delivered instantly' },
      { n: '03', title: 'We Build It', body: 'Choose your tier. We build every automation from the report — custom agents, integrations, and workflows — within days, not months.', note: 'Agent One from $499/mo' },
    ],
    defaultIndustry: 'E-commerce',
    serviceSchemaName: 'AI Automation for E-commerce & Online Retail',
    serviceSchemaDesc: 'E-commerce brands recover 10-15% abandoned cart revenue and cut stockouts by 40-60% with AI automation.',
  },

  accounting: {
    slug: 'accounting',
    name: 'Accounting Firms & CPAs',
    ogTitle: 'Stop Running Your Accounting Firm on Ghost Work — eevolvv',
    proSection: 'ACCOUNTING &amp; FINANCE',
    heroBeforeBr: 'Your accounting firm is running on',
    heroAfterBr: '<span style={{ color: \'var(--accent)\' }}>ghost work.</span>',
    heroBody: 'Document collection, data entry, categorization, reconciliation, monthly reporting — accounting firms lose 15–25 hours every week to tasks that should be automated. We find them, name them, and build the fix.',
    ctaText: 'GET FREE FIRM AUDIT →',
    ghostWorkTitle: 'Ghost work hiding in every accounting firm.',
    ghostWorkBody: 'These aren\'t inefficiencies you can hustle through. They\'re structural drains that compound every month — losing you billable hours, margin, and the time you should be spending on strategic advisory.',
    ghostWorkTotal: '16–25 hours per week recovered across a typical firm.',
    section3Title: 'Every firm type. One AI engine.',
    section4Title: 'Free audit. Custom report. Automations built for you.',
    resultSection: '§ 05 · RESULTS',
    tools: ['QuickBooks', 'Xero', 'FreshBooks', 'Keeper', 'Bill.com', 'Stripe', 'Hubdoc', 'Slack', 'TaxDome'],
    ghostWork: [
      { code: 'G-01', label: 'Document Collection', pain: 'Emailing clients for bank statements and receipts over and over — chasing documents daily', win: 'Automated document request sequences with reminders and secure upload portal', hrs: '4–6 hrs/wk' },
      { code: 'G-02', label: 'Data Entry & Categorization', pain: 'Manually categorizing transactions and fixing auto-categorization errors', win: 'AI-powered transaction categorization with confidence scoring and exception handling', hrs: '4–6 hrs/wk' },
      { code: 'G-03', label: 'Reconciliation', pain: 'Manually matching bank transactions to entries across multiple accounts', win: 'Automated reconciliation with match suggestions and discrepancy alerts', hrs: '3–5 hrs/wk' },
      { code: 'G-04', label: 'Monthly Reporting', pain: 'Compiling the same monthly financial packages for each client from scratch', win: 'Automated monthly report generation with branded templates and client portal delivery', hrs: '3–5 hrs/wk' },
      { code: 'G-05', label: 'Deadline Tracking', pain: 'Missing filing deadlines and extension dates because nobody tracks them proactively', win: 'Automated deadline calendar with client reminders and internal task assignments', hrs: '1–2 hrs/wk' },
      { code: 'G-06', label: 'Client Onboarding', pain: 'Welcome packets, engagement letters, prior-year data requests — all done manually', win: 'Automated onboarding sequence: engagement letter, data requests, portal setup, welcome', hrs: '2–3 hrs/client' },
    ],
    studioTypes: [
      { id: 'A-01', name: 'CPA Firms', note: 'Document collection, categorization, reconciliation, monthly reporting' },
      { id: 'A-02', name: 'Bookkeeping Services', note: 'Transaction processing, reconciliation, client reporting' },
      { id: 'A-03', name: 'Tax Preparation', note: 'Document collection, extension tracking, e-filing workflows' },
      { id: 'A-04', name: 'Financial Advisors', note: 'Review scheduling, portfolio reporting, compliance tracking' },
      { id: 'A-05', name: 'Payroll Services', note: 'Pay schedule automation, compliance alerts, onboarding flows' },
      { id: 'A-06', name: 'Audit Firms', note: 'Sampling workflows, evidence collection, report generation' },
      { id: 'A-07', name: 'Fractional CFO', note: 'Board reporting, cash flow dashboards, forecast automation' },
      { id: 'A-08', name: 'Virtual Accounting', note: 'Client communication hub, automated reporting, billing' },
    ],
    stats: [
      { value: '60–70%', label: 'faster document collection with automated request sequences' },
      { value: '80%', label: 'less manual reconciliation work with automation' },
      { value: '20–30%', label: 'improvement in collections with automated billing follow-up' },
      { value: '90%', label: 'fewer missed deadlines with automated calendar tracking' },
    ],
    testimonials: [
      { stat: '70% faster docs', quote: 'I used to spend 6 hours a week emailing clients for bank statements. Now the system requests them automatically and clients upload in minutes.', name: 'Lauren T.', biz: 'CPA Firm — Austin, TX' },
      { stat: '80% less reconciliation', quote: 'Transaction reconciliation used to take my team 8 hours per client per month. Now it flags exceptions only — we\'re 80% faster.', name: 'David K.', biz: 'Bookkeeping Service — Denver, CO' },
      { stat: '95% on-time filing', quote: 'Our deadline tracking used to be a whiteboard. Now automated reminders go to clients and staff — we hit 95% on-time filing this year.', name: 'Michelle R.', biz: 'Tax Firm — Dallas, TX' },
    ],
    processSteps: [
      { n: '01', title: 'AI Diagnostic', body: '10-minute AI conversation maps your operation — workflows, tools, pain points, team size, revenue. No forms. Just a conversation.', note: 'Free · No signup' },
      { n: '02', title: 'Evolution Report', body: 'Your custom report quantifies exactly how many hours you\'re losing, which automations will recover them first, and a 90-day build roadmap.', note: 'Delivered instantly' },
      { n: '03', title: 'We Build It', body: 'Choose your tier. We build every automation from the report — custom agents, integrations, and workflows — within days, not months.', note: 'Agent One from $499/mo' },
    ],
    defaultIndustry: 'Accounting / Finance',
    serviceSchemaName: 'AI Automation for Accounting Firms & CPAs',
    serviceSchemaDesc: 'CPA firms and bookkeeping services recover 15-25 hrs/week by automating document collection, data entry, and reporting.',
  },

  agency: {
    slug: 'agency',
    name: 'Marketing Agencies',
    ogTitle: 'Stop Running Your Agency on Ghost Work — eevolvv',
    proSection: 'AGENCIES &amp; CONSULTANCIES',
    heroBeforeBr: 'Your agency is running on',
    heroAfterBr: '<span style={{ color: \'var(--accent)\' }}>ghost work.</span>',
    heroBody: 'Client reporting, proposal generation, onboarding, retainer billing, resource allocation — agencies lose 15–20 hours per client every month to tasks that should be automated. We find them, name them, and build the fix.',
    ctaText: 'GET FREE AGENCY AUDIT →',
    ghostWorkTitle: 'Ghost work hiding in every agency.',
    ghostWorkBody: 'These aren\'t inefficiencies you can hustle through. They\'re structural drains that compound every month — losing you billable hours, margin, and the time you should be spending on creative work.',
    ghostWorkTotal: '16–26 hours per week recovered across a typical agency.',
    section3Title: 'Every agency type. One AI engine.',
    section4Title: 'Free audit. Custom report. Automations built for you.',
    resultSection: '§ 05 · RESULTS',
    tools: ['HubSpot', 'Asana', 'Monday.com', 'Slack', 'QuickBooks', 'Stripe', 'Google Ads', 'Meta Ads', 'Canva'],
    ghostWork: [
      { code: 'G-01', label: 'Client Reporting', pain: 'Manually pulling data from 5 platforms, building decks, and emailing each client separately', win: 'Automated white-label report delivery pulls live data and sends branded PDFs on a schedule', hrs: '3–6 hrs/client/mo' },
      { code: 'G-02', label: 'Proposal Generation', pain: 'Starting every proposal from scratch — same structure, same pricing math, different client name', win: 'Automated proposal templates with CRM-driven population, e-signature, and follow-up sequences', hrs: '3–5 hrs/wk' },
      { code: 'G-03', label: 'Client Onboarding', pain: 'New client signed — now 2 weeks of back-and-forth getting assets, access, and approvals', win: 'Automated onboarding sequence delivers asset requests, portal access, and meeting scheduling in one flow', hrs: '2–4 hrs/client' },
      { code: 'G-04', label: 'Retainer Billing & Renewal', pain: 'Manually generating invoices and then remembering to send renewal discussions 30 days out', win: 'Automated retainer billing runs + proactive renewal sequences 60 days before contract end', hrs: '2–3 hrs/wk' },
      { code: 'G-05', label: 'Campaign Scheduling', pain: 'Manually coordinating launch dates across platforms, clients, and internal teams', win: 'Automated campaign launch checklists with stakeholder sign-off gates and platform scheduling', hrs: '3–5 hrs/wk' },
      { code: 'G-06', label: 'Resource Allocation', pain: 'Manually tracking team utilization across projects and realizing you\'re overbooked too late', win: 'Automated utilization dashboard with overbooking alerts and capacity planning triggers', hrs: '2–4 hrs/wk' },
    ],
    studioTypes: [
      { id: 'AG-01', name: 'Digital Marketing Agencies', note: 'Multi-channel reporting, campaign management, client dashboards' },
      { id: 'AG-02', name: 'SEO Agencies', note: 'Rank tracking automation, link reporting, content scheduling' },
      { id: 'AG-03', name: 'Creative Agencies', note: 'Asset delivery workflows, approval gates, revision tracking' },
      { id: 'AG-04', name: 'PR Firms', note: 'Media monitoring, coverage reporting, pitch follow-up sequences' },
      { id: 'AG-05', name: 'Media Buying', note: 'Spend reporting, optimization alerts, client approval workflows' },
      { id: 'AG-06', name: 'Social Media Agencies', note: 'Content scheduling, engagement reporting, brand monitoring' },
      { id: 'AG-07', name: 'Content Agencies', note: 'Editorial calendar automation, writer briefing, delivery tracking' },
      { id: 'AG-08', name: 'Full-Service Agencies', note: 'Integrated reporting, project management, resource planning' },
    ],
    stats: [
      { value: '3–6 hrs', label: 'saved per client per month on manual reporting' },
      { value: '30–40%', label: 'faster sales cycle with automated proposals and contracts' },
      { value: '25%', label: 'less first-90-day churn with automated client onboarding' },
      { value: '15–20%', label: 'better retainer retention with renewal automation' },
    ],
    testimonials: [
      { stat: '6 hrs/client/mo saved', quote: 'We had someone spending 2 full days a week on client reports. Now reports generate automatically and clients love the real-time dashboard.', name: 'Jamie N.', biz: 'Digital Agency — Austin, TX' },
      { stat: '40% faster proposals', quote: 'Proposals went from half a day to 90 minutes. Our close rate actually improved because we\'re sending them faster.', name: 'Alex R.', biz: 'Creative Agency — Chicago, IL' },
      { stat: '30% less churn', quote: 'Our first-90-day churn dropped significantly once we automated the onboarding process. Clients felt set up for success from day one.', name: 'Sarah B.', biz: 'PR Firm — NYC, NY' },
    ],
    processSteps: [
      { n: '01', title: 'AI Diagnostic', body: '10-minute AI conversation maps your operation — workflows, tools, pain points, team size, revenue. No forms. Just a conversation.', note: 'Free · No signup' },
      { n: '02', title: 'Evolution Report', body: 'Your custom report quantifies exactly how many hours you\'re losing, which automations will recover them first, and a 90-day build roadmap.', note: 'Delivered instantly' },
      { n: '03', title: 'We Build It', body: 'Choose your tier. We build every automation from the report — custom agents, integrations, and workflows — within days, not months.', note: 'Agent One from $499/mo' },
    ],
    defaultIndustry: 'Marketing / Agency',
    serviceSchemaName: 'AI Automation for Marketing Agencies',
    serviceSchemaDesc: 'Marketing and creative agencies recover 15-20 hrs/client/month by automating reporting, proposals, and client onboarding.',
  },

  legal: {
    slug: 'legal',
    name: 'Law Firms',
    ogTitle: 'Stop Running Your Law Firm on Ghost Work — eevolvv',
    proSection: 'LEGAL &amp; LAW FIRMS',
    heroBeforeBr: 'Law firms recover',
    heroAfterBr: '<span style={{ color: \'var(--accent)\' }}>20+ billable hours/week</span> from intake, billing, and document admin.',
    heroBody: 'Client intake, document drafting, billing, collections, court reminders, status updates — law firms lose 15–20 hours of non-billable time every week to tasks that should be automated. We find them, name them, and build the fix.',
    ctaText: 'GET FREE FIRM AUDIT →',
    ghostWorkTitle: 'Ghost work hiding in every law firm.',
    ghostWorkBody: 'These aren\'t inefficiencies you can bill through. They\'re structural drains that compound every month — losing you clients, revenue, and the hours you should be spending on case strategy.',
    ghostWorkTotal: '16–28 hours per week recovered across a typical firm.',
    section3Title: 'Every practice area. One AI engine.',
    section4Title: 'Free audit. Custom report. Automations built for you.',
    resultSection: '§ 05 · RESULTS',
    tools: ['Clio', 'MyCase', 'PracticePanther', 'Lawmatics', 'CasePeer', 'Stripe', 'QuickBooks', 'Twilio', 'Slack'],
    ghostWork: [
      { code: 'G-01', label: 'Client Intake', pain: 'Screening inquiries manually, scheduling consultations one by one, missing leads after hours', win: 'Automated intake form + conflict check + consultation scheduling — qualified leads book directly', hrs: '4–6 hrs/wk' },
      { code: 'G-02', label: 'Document Assembly', pain: 'Drafting the same agreements, letters, and motions from scratch every time', win: 'Template-driven document automation cuts drafting time by 60–80% on standard matter types', hrs: '4–8 hrs/wk' },
      { code: 'G-03', label: 'Billing & Time Capture', pain: 'Reconstructing time entries at the end of the week from memory — losing 1–2 hours of billable time daily', win: 'Automated time-capture prompts + billing run automation with AR follow-up sequences', hrs: '3–5 hrs/wk' },
      { code: 'G-04', label: 'Collections Follow-Up', pain: 'Sending billing reminders manually and tracking who owes what across matters', win: 'Automated 7/21/45-day collections sequences with escalation triggers — collections improve 20–35%', hrs: '2–4 hrs/wk' },
      { code: 'G-05', label: 'Court Date Reminders', pain: 'Manually calling clients to remind them of hearings, deadlines, and appointments', win: 'Automated deadline and court date reminders via text and email — no-shows drop significantly', hrs: '1–2 hrs/wk' },
      { code: 'G-06', label: 'Matter Status Updates', pain: 'Clients calling for updates because no proactive communication went out', win: 'Automated milestone notifications at every stage of the matter lifecycle', hrs: '2–3 hrs/wk' },
    ],
    studioTypes: [
      { id: 'L-01', name: 'Personal Injury', note: 'Lead intake funnels, medical record tracking, settlement sequences' },
      { id: 'L-02', name: 'Family Law', note: 'Sensitive intake flows, document collection, calendar coordination' },
      { id: 'L-03', name: 'Estate Planning', note: 'Consultation booking, document delivery, annual review campaigns' },
      { id: 'L-04', name: 'Business Law', note: 'Contract automation, entity management, retainer renewals' },
      { id: 'L-05', name: 'Criminal Defense', note: 'After-hours intake, court date tracking, client communication' },
      { id: 'L-06', name: 'Real Estate Law', note: 'Transaction coordination, title document workflows, closing sequences' },
      { id: 'L-07', name: 'Employment Law', note: 'Intake screening, statute deadline tracking, settlement workflows' },
      { id: 'L-08', name: 'Immigration', note: 'Application status updates, deadline reminders, document checklists' },
    ],
    stats: [
      { value: '40–60%', label: 'reduction in intake admin with automated screening workflows' },
      { value: '60–80%', label: 'faster document drafting on standard templates' },
      { value: '20–35%', label: 'improvement in collections with automated billing reminders' },
      { value: '30–50%', label: 'fewer inbound status calls with automated matter updates' },
    ],
    testimonials: [
      { stat: '60% faster drafting', quote: 'We cut standard document drafting time by 60%. What used to take a paralegal 3 hours now takes 45 minutes with automated templates.', name: 'David C.', biz: 'Business Law — Dallas, TX' },
      { stat: '5 hrs/wk recovered', quote: 'The automated intake and scheduling system means we never miss a lead after hours. We\'ve captured 12 new consults in the first month alone.', name: 'Rachel M.', biz: 'Personal Injury — Austin, TX' },
      { stat: '30% better collections', quote: 'Our collection rate on aged receivables went from 55% to 85%. The automated dunning sequence removes the awkwardness of chasing payment.', name: 'Tom K.', biz: 'Family Law — Denver, CO' },
    ],
    processSteps: [
      { n: '01', title: 'AI Diagnostic', body: '10-minute AI conversation maps your operation — workflows, tools, pain points, team size, revenue. No forms. Just a conversation.', note: 'Free · No signup' },
      { n: '02', title: 'Evolution Report', body: 'Your custom report quantifies exactly how many hours you\'re losing, which automations will recover them first, and a 90-day build roadmap.', note: 'Delivered instantly' },
      { n: '03', title: 'We Build It', body: 'Choose your tier. We build every automation from the report — custom agents, integrations, and workflows — within days, not months.', note: 'Agent One from $499/mo' },
    ],
    defaultIndustry: 'Legal',
    serviceSchemaName: 'AI Automation for Law Firms',
    serviceSchemaDesc: 'Law firms recover 15-20 hrs/week of non-billable time by automating intake, billing, and document workflows.',
  },

  'real-estate': {
    slug: 'real-estate',
    name: 'Real Estate Agents & Brokerages',
    ogTitle: 'Stop Running Your Real Estate Business on Ghost Work — eevolvv',
    proSection: 'REAL ESTATE',
    heroBeforeBr: 'Real estate teams close',
    heroAfterBr: '<span style={{ color: \'var(--accent)\' }}>2–4 extra deals/month</span> with instant lead response and automated follow-up.',
    heroBody: 'Lead response delays, CRM neglect, showing coordination, transaction milestones, post-close follow-up — agents lose 15–25 hours every week to tasks that should be automated. We find them, name them, and build the fix.',
    ctaText: 'GET FREE AGENT AUDIT →',
    ghostWorkTitle: 'Ghost work hiding in every real estate business.',
    ghostWorkBody: 'These aren\'t inefficiencies you can "get organized" through. They\'re structural drains that compound every month — losing you deals, commissions, and the hours you should be spending with clients.',
    ghostWorkTotal: '15–25 hours per week recovered across a typical agent.',
    section3Title: 'Every real estate professional. One AI engine.',
    section4Title: 'Free audit. Custom report. Automations built for you.',
    resultSection: '§ 05 · RESULTS',
    tools: ['Follow Up Boss', 'KVCore', 'BoomTown', 'Slack', 'Stripe', 'QuickBooks', 'Mailchimp', 'Twilio', 'Calendly'],
    ghostWork: [
      { code: 'G-01', label: 'Lead Response Delay', pain: 'A new inquiry comes in at 8pm — you respond the next morning. They\'ve already signed with someone else', win: 'Automated instant lead response + 14-day nurture sequence converts leads before they go cold', hrs: '3–5 hrs/wk' },
      { code: 'G-02', label: 'CRM Hygiene', pain: 'Contact records going stale, notes missing, follow-up tasks falling through the cracks', win: 'Automated CRM update triggers after every showing, call, and offer — database stays clean', hrs: '3–4 hrs/wk' },
      { code: 'G-03', label: 'Showing Coordination', pain: 'Going back and forth with buyers, sellers, and agents to schedule showings manually', win: 'Automated showing scheduling with instant confirmation and 24-hr reminders for all parties', hrs: '2–4 hrs/wk' },
      { code: 'G-04', label: 'Transaction Milestones', pain: 'Manually tracking inspection deadlines, contingency dates, and closing tasks across every deal', win: 'Automated transaction timeline with milestone alerts to clients, agents, and TCs', hrs: '3–5 hrs/wk' },
      { code: 'G-05', label: 'Post-Close Follow-Up', pain: 'Closing the deal and then going silent — missing the best window for referrals and reviews', win: 'Automated 12-month post-close sequence: anniversary messages, market updates, referral asks', hrs: '2–3 hrs/wk' },
      { code: 'G-06', label: 'Market Report Distribution', pain: 'Manually compiling and emailing market reports to your sphere every month', win: 'Automated monthly market update delivery to your full contact database, personalized by area', hrs: '2–4 hrs/wk' },
    ],
    studioTypes: [
      { id: 'RE-01', name: 'Residential Agents', note: 'Lead nurture, showing automation, post-close sequences' },
      { id: 'RE-02', name: 'Luxury Agents', note: 'High-touch follow-up, private listing alerts, concierge sequences' },
      { id: 'RE-03', name: 'Commercial Brokers', note: 'Deal pipeline tracking, LOI coordination, market reporting' },
      { id: 'RE-04', name: 'Property Managers', note: 'Lease renewal campaigns, maintenance coordination, tenant comms' },
      { id: 'RE-05', name: 'Buyer\'s Agents', note: 'Search alerts, offer tracking, pre-approval follow-up sequences' },
      { id: 'RE-06', name: 'Listing Specialists', note: 'Seller lead nurture, market valuation sequences, offer management' },
      { id: 'RE-07', name: 'Real Estate Teams', note: 'Lead routing, team reporting, agent accountability dashboards' },
      { id: 'RE-08', name: 'Brokerages', note: 'Recruiting automation, agent onboarding, production reporting' },
    ],
    stats: [
      { value: '9×', label: 'more leads converted when response happens within 5 minutes' },
      { value: '5–8 hrs', label: 'saved per transaction via automated coordination workflows' },
      { value: '30–40%', label: 'of top agent revenue comes from automated referral campaigns' },
      { value: '40%', label: 'reduction in per-agent admin time with CRM automation' },
    ],
    testimonials: [
      { stat: '9x lead conversion', quote: 'When my team started responding to website leads within 90 seconds using automated SMS, our lead-to-showing conversion tripled. Time kills deals.', name: 'Marcus T.', biz: 'Real Estate Team — Austin, TX' },
      { stat: '8 hrs/deal saved', quote: 'Transaction coordination used to be my biggest time sink. Now milestone alerts keep everyone on track without me chasing. I\'ve closed 3 more deals this quarter.', name: 'Jessica K.', biz: 'Residential Agent — Dallas, TX' },
      { stat: '+40% referral revenue', quote: 'The 12-month post-close sequence keeps me top-of-mind with past clients. My referral revenue jumped 40% in the first 6 months.', name: 'Ryan P.', biz: 'Luxury Agent — Denver, CO' },
    ],
    processSteps: [
      { n: '01', title: 'AI Diagnostic', body: '10-minute AI conversation maps your operation — workflows, tools, pain points, team size, revenue. No forms. Just a conversation.', note: 'Free · No signup' },
      { n: '02', title: 'Evolution Report', body: 'Your custom report quantifies exactly how many hours you\'re losing, which automations will recover them first, and a 90-day build roadmap.', note: 'Delivered instantly' },
      { n: '03', title: 'We Build It', body: 'Choose your tier. We build every automation from the report — custom agents, integrations, and workflows — within days, not months.', note: 'Agent One from $499/mo' },
    ],
    defaultIndustry: 'Real Estate',
    serviceSchemaName: 'AI Automation for Real Estate Agents & Brokerages',
    serviceSchemaDesc: 'Real estate agents and brokerages recover 15-25 hrs/week by automating follow-up and transaction coordination.',
  },
}

export const VERTICAL_SLUGS = Object.keys(VERTICALS)
export type VerticalSlug = keyof typeof VERTICALS