import Stripe from 'stripe'
import { supabase } from '@/lib/supabase'
import { getTierFromPriceId, type Tier } from '@/lib/stripe-prices'
import {
  sendWelcomeEmail,
  sendOnboardingEmail,
  sendPaymentFailed,
  sendFirstFixWelcome,
  sendIntakePilotKickoff,
  sendTextbackPilotKickoff,
} from '@/lib/email-helpers'
import { stripe } from '@/lib/stripe'
import { getPostHogClient } from '@/lib/posthog-server'

type PilotProductType = 'intake-pilot' | 'textback-pilot'

/**
 * Create client record, subscription, onboarding token, and initial build entry
 * after a successful Stripe checkout. Idempotent on stripe_subscription_id.
 */
export async function createClientRecord(
  session: Stripe.Checkout.Session
): Promise<void> {
  if (!supabase) {
    console.error('[webhook-handlers] Supabase not configured — cannot create client record')
    return
  }

  const sessionId = session.id
  const email = session.customer_details?.email ?? session.customer_email ?? ''
  const name = session.customer_details?.name ?? ''
  const stripeCustomerId =
    typeof session.customer === 'string'
      ? session.customer
      : (session.customer as Stripe.Customer | null)?.id ?? ''

  // Derive tier from metadata (set by T03) or fall back to price ID
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const rawSession = session as Record<string, any>
  let tier: Tier = (rawSession.metadata?.tier as Tier) ?? null
  if (!tier) {
    // Try to get from subscription metadata
    const priceId =
      rawSession.metadata?.priceId ??
      rawSession.line_items?.data?.[0]?.price?.id ??
      ''
    tier = (priceId ? getTierFromPriceId(priceId) : null) ?? 'seed'
    if (!priceId) {
      console.warn('[webhook-handlers] Could not derive tier from metadata for session', sessionId, '— defaulting to seed')
    }
  }

  const interval = (rawSession.metadata?.interval as 'monthly' | 'annual') ?? 'monthly'
  const stripeSubscriptionId =
    typeof session.subscription === 'string'
      ? session.subscription
      : (session.subscription as Stripe.Subscription | null)?.id ?? ''

  if (!email || !stripeSubscriptionId) {
    console.error('[webhook-handlers] Missing required fields', { email: !!email, stripeSubscriptionId: !!stripeSubscriptionId, sessionId })
    return
  }

  // ── Idempotency check ──────────────────────────────────────────────────────
  const { data: existingSub } = await supabase
    .from('subscriptions')
    .select('id, client_id')
    .eq('stripe_subscription_id', stripeSubscriptionId)
    .maybeSingle()

  if (existingSub) {
    console.log('[webhook-handlers] createClientRecord: already processed', stripeSubscriptionId)
    return
  }

  // ── Create or find client ──────────────────────────────────────────────────
  let clientId: string

  const { data: existingClient } = await supabase
    .from('clients')
    .select('id')
    .eq('email', email)
    .maybeSingle()

  if (existingClient) {
    clientId = existingClient.id
    // Update with latest Stripe info
    await supabase
      .from('clients')
      .update({
        stripe_customer_id: stripeCustomerId || undefined,
        tier,
        churn_risk: false,
      })
      .eq('id', clientId)
  } else {
    const { data: newClient, error: clientErr } = await supabase
      .from('clients')
      .insert({
        email,
        name,
        company: name, // company = name at signup; technician updates later
        stripe_customer_id: stripeCustomerId || undefined,
        tier,
        churn_risk: false,
      })
      .select('id')
      .single()

    if (clientErr || !newClient) {
      console.error('[webhook-handlers] Failed to create client:', clientErr?.message)
      return
    }
    clientId = newClient.id
  }

  // ── Create subscription record ─────────────────────────────────────────────
  const { error: subErr } = await supabase
    .from('subscriptions')
    .insert({
      client_id: clientId,
      stripe_subscription_id: stripeSubscriptionId,
      stripe_price_id: rawSession.metadata?.priceId ?? '',
      status: 'active',
      billing_interval: interval,
      current_period_end: null, // Updated by subscription.updated webhook
    })

  if (subErr) {
    console.error('[webhook-handlers] Failed to create subscription:', subErr.message)
    return
  }

  // ── Create onboarding token ────────────────────────────────────────────────
  const { data: tokenRow, error: tokenErr } = await supabase
    .from('onboarding_tokens')
    .insert({
      client_id: clientId,
      // token auto-generated by DB: encode(gen_random_bytes(32), 'hex')
      status: 'pending',
      expires_at: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000).toISOString(),
    })
    .select('token')
    .single()

  if (tokenErr || !tokenRow) {
    console.error('[webhook-handlers] Failed to create onboarding token:', tokenErr?.message)
    return
  }

  // ── Create initial build record ────────────────────────────────────────────
  const { error: buildErr } = await supabase
    .from('builds')
    .insert({
      client_id: clientId,
      tier,
      status: 'queued',
    })

  if (buildErr) {
    // Non-fatal — log and continue to email sending
    console.error('[webhook-handlers] Failed to create build record:', buildErr.message)
  }

  // ── Send emails (non-blocking) ─────────────────────────────────────────────
  const firstName = name.split(' ')[0] || 'there'

  ;(async () => {
    try {
      await sendWelcomeEmail({ email, name: firstName, tier })
      await sendOnboardingEmail({ email, name: firstName, tier, token: tokenRow.token })
    } catch (err) {
      console.error('[webhook-handlers] Email send failed:', err)
      // Non-fatal — client record exists, emails can be re-sent manually
    }
  })()

  const baseUrl = process.env.NEXT_PUBLIC_BASE_URL ?? 'https://eevolvv.com'
  console.log('[webhook-handlers] createClientRecord complete', {
    clientId,
    tier,
    stripeSubscriptionId,
    onboardingUrl: `${baseUrl}/onboard/${tokenRow.token}`,
  })
}

/**
 * Handle First Fix one-time purchase.
 * Creates a client record (no subscription), a build record, sends welcome email,
 * and creates a testimonial row so the 14-day request can fire later.
 */
export async function handleFirstFixCompleted(
  session: Stripe.Checkout.Session
): Promise<void> {
  if (!supabase) { console.error('[webhook-handlers] Supabase not configured'); return }

  const email = session.customer_details?.email ?? session.customer_email ?? ''
  const name = session.customer_details?.name ?? ''
  const stripeCustomerId =
    typeof session.customer === 'string'
      ? session.customer
      : (session.customer as Stripe.Customer | null)?.id ?? ''

  if (!email) { console.error('[webhook-handlers] handleFirstFixCompleted: no email on session', session.id); return }

  // Idempotency: check if we already processed this session
  const { data: existingBuild } = await supabase
    .from('builds')
    .select('id')
    .eq('stripe_session_id', session.id)
    .maybeSingle()

  if (existingBuild) {
    console.log('[webhook-handlers] handleFirstFixCompleted: already processed', session.id)
    return
  }

  // Create or find client
  let clientId: string
  const { data: existingClient } = await supabase
    .from('clients')
    .select('id')
    .eq('email', email)
    .maybeSingle()

  if (existingClient) {
    clientId = existingClient.id
    await supabase.from('clients').update({ stripe_customer_id: stripeCustomerId || undefined }).eq('id', clientId)
  } else {
    const { data: newClient, error: clientErr } = await supabase
      .from('clients')
      .insert({ email, name, company: name, stripe_customer_id: stripeCustomerId || undefined, tier: 'first-fix', churn_risk: false })
      .select('id')
      .single()
    if (clientErr || !newClient) { console.error('[webhook-handlers] handleFirstFixCompleted: client insert error:', clientErr?.message); return }
    clientId = newClient.id
  }

  // Create build record flagged as first-fix
  await supabase.from('builds').insert({
    client_id: clientId,
    tier: 'seed',
    status: 'queued',
    stripe_session_id: session.id,
    notes: 'first-fix',
  })

  // Create testimonial row with token (will send request email at T+14d via cron)
  await supabase.from('testimonials').insert({
    client_email: email,
    client_name: name || undefined,
    source: 'first-fix',
    published: false,
  })

  // Notify admin
  const BASE_URL = process.env.NEXT_PUBLIC_BASE_URL ?? 'https://eevolvv.com'
  console.log('[webhook-handlers] handleFirstFixCompleted complete', { clientId, email, adminUrl: `${BASE_URL}/os` })

  // Send welcome email (non-blocking)
  ;(async () => {
    try {
      await sendFirstFixWelcome({ email, name: name || undefined })
    } catch (err) {
      console.error('[webhook-handlers] handleFirstFixCompleted welcome email error:', err)
    }
  })()

  // PostHog event
  const ph = getPostHogClient()
  const distinctId = (typeof session.customer === 'string' ? session.customer : null) ?? session.id
  ph.capture({ distinctId, event: 'first_fix_purchased', properties: { amount: session.amount_total != null ? session.amount_total / 100 : null } })
  await ph.shutdown()
}

/**
 * Handle pilot product purchases (intake-pilot, textback-pilot).
 * Creates client record, build entry (with product_type + stripe_session_id),
 * onboarding token (product_type-aware), testimonials row, and sends kickoff email.
 */
export async function handlePilotCompleted(
  session: Stripe.Checkout.Session,
  productType: PilotProductType
): Promise<void> {
  if (!supabase) { console.error('[webhook-handlers] handlePilotCompleted: Supabase not configured'); return }

  const email = session.customer_details?.email ?? session.customer_email ?? ''
  const name = session.customer_details?.name ?? ''
  const stripeCustomerId =
    typeof session.customer === 'string'
      ? session.customer
      : (session.customer as Stripe.Customer | null)?.id ?? ''

  if (!email) {
    console.error('[webhook-handlers] handlePilotCompleted: no email on session', session.id)
    return
  }

  // Idempotency: check if we already processed this session
  const { data: existingBuild } = await supabase
    .from('builds')
    .select('id')
    .eq('stripe_session_id', session.id)
    .maybeSingle()

  if (existingBuild) {
    console.log('[webhook-handlers] handlePilotCompleted: already processed', session.id)
    return
  }

  // Create or find client
  let clientId: string
  const { data: existingClient } = await supabase
    .from('clients')
    .select('id')
    .eq('email', email)
    .maybeSingle()

  if (existingClient) {
    clientId = existingClient.id
    await supabase.from('clients').update({
      stripe_customer_id: stripeCustomerId || undefined,
    }).eq('id', clientId)
  } else {
    const { data: newClient, error: clientErr } = await supabase
      .from('clients')
      .insert({
        email,
        name,
        company: name,
        stripe_customer_id: stripeCustomerId || undefined,
        tier: 'seed', // pilot clients default to seed tier for portal access
        churn_risk: false,
      })
      .select('id')
      .single()
    if (clientErr || !newClient) {
      console.error('[webhook-handlers] handlePilotCompleted: client insert error:', clientErr?.message)
      return
    }
    clientId = newClient.id
  }

  // Create build record — tier maps to the pilot product type
  const tierForBuild = productType === 'intake-pilot' ? 'intake-pilot' : 'textback-pilot'
  const { error: buildErr } = await supabase.from('builds').insert({
    client_id: clientId,
    tier: tierForBuild,
    status: 'queued',
    stripe_session_id: session.id,
    product_type: productType,
    notes: `${productType} — auto-created from Stripe checkout ${session.id}`,
  })
  if (buildErr) {
    console.error('[webhook-handlers] handlePilotCompleted: build insert error:', buildErr.message)
    // Non-fatal — continue to token + email
  }

  // Create onboarding token with product_type so the intake form asks the right questions
  const { data: tokenRow, error: tokenErr } = await supabase
    .from('onboarding_tokens')
    .insert({
      client_id: clientId,
      status: 'pending',
      product_type: productType,
      expires_at: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000).toISOString(),
    })
    .select('token')
    .single()

  if (tokenErr || !tokenRow) {
    console.error('[webhook-handlers] handlePilotCompleted: token insert error:', tokenErr?.message)
  }

  // Create testimonial row for T+14d request
  await supabase.from('testimonials').insert({
    client_email: email,
    client_name: name || undefined,
    source: productType,
    published: false,
  }).then(({ error }) => {
    if (error) console.error('[webhook-handlers] handlePilotCompleted: testimonial insert error:', error.message)
  })

  const BASE_URL = process.env.NEXT_PUBLIC_BASE_URL ?? 'https://eevolvv.com'
  const onboardingUrl = tokenRow ? `${BASE_URL}/onboard/${tokenRow.token}` : `${BASE_URL}/onboard/success?product=${productType}`
  console.log('[webhook-handlers] handlePilotCompleted complete', { clientId, email, productType, onboardingUrl })

  // Send kickoff email (non-blocking)
  ;(async () => {
    try {
      const firstName = name.split(' ')[0] || 'there'
      if (productType === 'intake-pilot') {
        await sendIntakePilotKickoff({ email, name: firstName })
      } else {
        await sendTextbackPilotKickoff({ email, name: firstName })
      }
    } catch (err) {
      console.error('[webhook-handlers] handlePilotCompleted kickoff email error:', err)
    }
  })()

  // PostHog event
  const ph = getPostHogClient()
  const distinctId = (typeof session.customer === 'string' ? session.customer : null) ?? session.id
  ph.capture({
    distinctId,
    event: 'pilot_purchased',
    properties: {
      product_type: productType,
      amount: session.amount_total != null ? session.amount_total / 100 : null,
      client_id: clientId,
    },
  })
  await ph.shutdown()
}

/**
 * Handle checkout.session.completed
 */
export async function handleCheckoutSessionCompleted(
  session: Stripe.Checkout.Session
): Promise<void> {
  // Route by product type
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const product = (session as Record<string, any>).metadata?.product

  // Pilot products — create client record + build + kickoff email
  if (product === 'intake-pilot' || product === 'textback-pilot') {
    await handlePilotCompleted(session, product as PilotProductType)
    return
  }

  // First Fix — custom one-time build
  if (product === 'first-fix') {
    await handleFirstFixCompleted(session)
    return
  }

  // Report-roadmap and other simple one-time products — no client record needed
  if (product === 'report-roadmap' || product === 'intake-monthly' || product === 'textback-monthly') {
    const ph = getPostHogClient()
    const distinctId = (typeof session.customer === 'string' ? session.customer : null) ?? session.id
    ph.capture({ distinctId, event: 'cash_product_purchased', properties: { product, amount: session.amount_total != null ? session.amount_total / 100 : null } })
    await ph.shutdown()
    return
  }

  // No product metadata → subscription checkout
  await createClientRecord(session)

  // T24: checkout_completed — distinctId is Stripe customer ID (opaque, no PII)
  const ph = getPostHogClient()
  const distinctId =
    (typeof session.customer === 'string' ? session.customer : null) ?? session.id
  ph.capture({
    distinctId,
    event: 'checkout_completed',
    properties: {
      tier: session.metadata?.tier ?? '',
      interval: session.metadata?.interval ?? '',
      amount: session.amount_total != null ? session.amount_total / 100 : null,
    },
  })
  await ph.shutdown()
}

/**
 * Handle invoice.payment_succeeded
 * Updates subscription status to active.
 */
export async function handleInvoicePaymentSucceeded(
  invoice: Stripe.Invoice
): Promise<void> {
  if (!supabase) return
  // Access subscription ID — Stripe 2026 API shape may vary
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const rawInvoice = invoice as Record<string, any>
  const subscriptionId: string | undefined =
    rawInvoice.subscription_id ??
    (typeof rawInvoice.subscription === 'string' ? rawInvoice.subscription : rawInvoice.subscription?.id)
  if (!subscriptionId) return
  const { error } = await supabase
    .from('subscriptions')
    .update({ status: 'active', updated_at: new Date().toISOString() })
    .eq('stripe_subscription_id', subscriptionId)
  if (error) console.error('[webhook-handlers] payment_succeeded update error:', error.message)
}

/**
 * Handle invoice.payment_failed
 * Updates subscription to past_due and sends dunning email with Stripe billing portal link.
 */
export async function handleInvoicePaymentFailed(
  invoice: Stripe.Invoice
): Promise<void> {
  if (!supabase) { console.error('[webhook-handlers] Supabase not configured'); return }

  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const rawInvoice = invoice as Record<string, any>
  const subscriptionId: string =
    rawInvoice.subscription_id ??
    (typeof rawInvoice.subscription === 'string' ? rawInvoice.subscription : rawInvoice.subscription?.id) ??
    ''

  if (!subscriptionId) {
    console.warn('[webhook-handlers] payment_failed: no subscription ID on invoice', invoice.id)
    return
  }

  // Update subscription status to past_due
  const { data: sub, error: subErr } = await supabase
    .from('subscriptions')
    .update({ status: 'past_due', updated_at: new Date().toISOString() })
    .eq('stripe_subscription_id', subscriptionId)
    .select('client_id')
    .single()

  if (subErr || !sub) {
    console.error('[webhook-handlers] payment_failed: subscription update error:', subErr?.message)
    return
  }

  // Fetch client for email
  const { data: client } = await supabase
    .from('clients')
    .select('email, name, tier, stripe_customer_id')
    .eq('id', sub.client_id)
    .single()

  if (!client?.email) {
    console.warn('[webhook-handlers] payment_failed: no client email for client_id', sub.client_id)
    return
  }

  // Build billing portal URL — try Stripe portal first, fall back to /pricing
  const BASE_URL = process.env.NEXT_PUBLIC_BASE_URL ?? 'https://eevolvv.com'
  let billingPortalUrl = `${BASE_URL}/pricing`

  if (stripe && client.stripe_customer_id) {
    try {
      const { data: tokenRow } = await supabase
        .from('onboarding_tokens')
        .select('token')
        .eq('client_id', sub.client_id)
        .maybeSingle()

      const returnUrl = tokenRow?.token
        ? `${BASE_URL}/client/${tokenRow.token}`
        : `${BASE_URL}/pricing`

      const session = await stripe.billingPortal.sessions.create({
        customer: client.stripe_customer_id,
        return_url: returnUrl,
      })
      billingPortalUrl = session.url
    } catch (err) {
      console.error('[webhook-handlers] billing portal creation failed:', err)
    }
  }

  const amountDue = rawInvoice.amount_due
    ? `$${(rawInvoice.amount_due / 100).toFixed(2)}`
    : undefined

  ;(async () => {
    await sendPaymentFailed({
      email: client.email!,
      name: client.name ?? undefined,
      amountDue,
      tier: client.tier ?? undefined,
      billingPortalUrl,
    })
  })()

  console.log('[webhook-handlers] payment_failed handled for subscription:', subscriptionId)
}

/**
 * Handle customer.subscription.updated
 */
export async function handleSubscriptionUpdated(
  subscription: Stripe.Subscription
): Promise<void> {
  if (!supabase) return
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const rawSub = subscription as Record<string, any>
  const periodEnd = rawSub.current_period_end
  const periodEndIso =
    typeof periodEnd === 'number'
      ? new Date(periodEnd * 1000).toISOString()
      : typeof periodEnd === 'string'
      ? periodEnd
      : null
  const { error } = await supabase
    .from('subscriptions')
    .update({
      status: subscription.status,
      ...(periodEndIso ? { current_period_end: periodEndIso } : {}),
      cancel_at_period_end: subscription.cancel_at_period_end,
      updated_at: new Date().toISOString(),
    })
    .eq('stripe_subscription_id', subscription.id)
  if (error) console.error('[webhook-handlers] subscription_updated error:', error.message)
}

/**
 * Handle customer.subscription.deleted
 * Marks subscription canceled, flags client as churn risk, pauses non-live builds.
 */
export async function handleSubscriptionDeleted(
  subscription: Stripe.Subscription
): Promise<void> {
  if (!supabase) { console.error('[webhook-handlers] Supabase not configured'); return }

  // Update subscription status to canceled
  const { data: sub } = await supabase
    .from('subscriptions')
    .update({ status: 'canceled', updated_at: new Date().toISOString() })
    .eq('stripe_subscription_id', subscription.id)
    .select('client_id')
    .maybeSingle()

  if (!sub?.client_id) {
    console.warn('[webhook-handlers] subscription_deleted: no matching record for', subscription.id)
    return
  }

  // Flag client as churn risk
  await supabase
    .from('clients')
    .update({ churn_risk: true })
    .eq('id', sub.client_id)

  // Pause all non-live, non-failed builds for this client
  const { error: buildErr } = await supabase
    .from('builds')
    .update({ status: 'paused', updated_at: new Date().toISOString() })
    .eq('client_id', sub.client_id)
    .not('status', 'in', '(live,failed)')

  if (buildErr) {
    console.error('[webhook-handlers] subscription_deleted: build pause error:', buildErr.message)
  }

  console.log('[webhook-handlers] subscription_deleted handled:', subscription.id, 'client:', sub.client_id)
}
