import * as React from 'react'
import {
  Html,
  Head,
  Body,
  Container,
  Section,
  Text,
  Heading,
  Button,
  Hr,
  Preview,
  Font,
} from '@react-email/components'

interface Props {
  name?: string
  businessName?: string
  businessType?: string
  industry?: string
  tier?: string
  report: string
}

const TIER_LABELS: Record<string, string> = {
  seed: 'Seed — AI Starter ($500–$1,500)',
  grow: 'Grow — AI Essentials ($3,500–$7,500)',
  scale: 'Scale — AI Transformation ($15,000–$75,000)',
  enterprise: 'Enterprise — AI Operations ($50,000–$250,000+)',
  retainer: 'Evolve Retainer ($500–$25K/mo)',
  unsure: 'Not sure yet',
}

function parseReport(raw: string): Array<{ heading: string; body: string }> {
  const sections: Array<{ heading: string; body: string }> = []
  const chunks = raw.split(/(?=###\s)/)
  for (const chunk of chunks) {
    const match = chunk.match(/^###\s+(.+?)\n([\s\S]*)$/)
    if (match) {
      sections.push({ heading: match[1].trim(), body: match[2].trim() })
    } else if (chunk.trim()) {
      sections.push({ heading: '', body: chunk.trim() })
    }
  }
  return sections
}

export function EvolutionReportEmail({
  name,
  businessName,
  businessType,
  industry,
  tier,
  report,
}: Props) {
  const displayName = businessName || businessType || 'your business'
  const greeting = name ? `Hi ${name.split(' ')[0]},` : 'Hi,'
  const sections = parseReport(report)
  const tierLabel = TIER_LABELS[tier ?? ''] ?? tier

  return (
    <Html lang="en" dir="ltr">
      <Head>
        <Font
          fontFamily="Helvetica Neue"
          fallbackFontFamily="Helvetica"
          webFont={undefined}
          fontWeight={400}
          fontStyle="normal"
        />
      </Head>
      <Preview>Your eevolvv report for {displayName} is ready — AI-powered automation roadmap inside.</Preview>
      <Body style={body}>
        <Container style={container}>

          {/* Header */}
          <Section style={header}>
            <Text style={logoText}>EEVOLVV</Text>
            <Text style={tagline}>AI BUSINESS TRANSFORMATION</Text>
          </Section>

          {/* Intro */}
          <Section style={introSection}>
            <Text style={greetingText}>{greeting}</Text>
            <Text style={introText}>
              Your AI-powered eevolvv report for <strong style={highlight}>{displayName}</strong> is ready.
              This diagnostic was generated by our AI engine based on your intake data — every number and recommendation is specific to your business.
            </Text>
            {industry && (
              <Text style={metaText}>Industry: {industry}{tierLabel ? ` · Tier: ${tierLabel}` : ''}</Text>
            )}
          </Section>

          <Hr style={divider} />

          {/* Report sections */}
          {sections.map((section, i) => (
            <Section key={i} style={reportSection}>
              {section.heading && (
                <Heading as="h2" style={sectionHeading}>
                  {section.heading}
                </Heading>
              )}
              {section.body.split('\n').map((line, j) => {
                const stripped = line.trim()
                if (!stripped) return null
                if (stripped.startsWith('**') && stripped.endsWith('**')) {
                  return (
                    <Text key={j} style={boldLine}>
                      {stripped.replace(/\*\*/g, '')}
                    </Text>
                  )
                }
                if (stripped.startsWith('-') || stripped.startsWith('•')) {
                  return (
                    <Text key={j} style={bulletLine}>
                      → {stripped.replace(/^[-•]\s*/, '')}
                    </Text>
                  )
                }
                return (
                  <Text key={j} style={bodyText}>
                    {stripped.replace(/\*\*(.*?)\*\*/g, '$1')}
                  </Text>
                )
              })}
            </Section>
          ))}

          <Hr style={divider} />

          {/* CTA */}
          <Section style={ctaSection}>
            <Heading as="h3" style={ctaHeading}>Ready to make this real?</Heading>
            <Text style={ctaText}>
              Book your free 30-minute strategy call. We&apos;ll walk through your roadmap together and confirm the right starting point for your business.
            </Text>
            <Button
              href="https://calendly.com/hello-eevolvv"
              style={ctaButton}
            >
              Book Your Strategy Call →
            </Button>
          </Section>

          <Hr style={divider} />

          {/* Footer */}
          <Section style={footerSection}>
            <Text style={footerText}>
              eevolvv &nbsp;·&nbsp; eevolvv.com &nbsp;·&nbsp;{' '}
              <a href="mailto:hello@eevolvv.com" style={footerLink}>hello@eevolvv.com</a>
            </Text>
            <Text style={footerSmall}>
              60-day structured audit on Transformation engagements.
              This report was generated by AI and is confidential to {displayName}.
            </Text>
          </Section>

        </Container>
      </Body>
    </Html>
  )
}

export default EvolutionReportEmail

// ── Styles ────────────────────────────────────────────────────────────────────

const INK = '#141413'
const PAPER = '#faf7f0'
const RULE = 'rgba(20,20,19,0.14)'
const ACCENT = '#8B2A1A'

const body: React.CSSProperties = {
  backgroundColor: '#ede9df',
  fontFamily: '"Helvetica Neue", Helvetica, Arial, sans-serif',
  margin: 0,
  padding: '32px 0',
}

const container: React.CSSProperties = {
  maxWidth: '600px',
  margin: '0 auto',
  backgroundColor: PAPER,
  border: `1px solid ${INK}`,
}

const header: React.CSSProperties = {
  backgroundColor: INK,
  padding: '28px 40px 24px',
  borderBottom: `1px solid ${RULE}`,
  textAlign: 'center',
}

const logoText: React.CSSProperties = {
  color: PAPER,
  fontSize: '20px',
  fontWeight: 700,
  letterSpacing: '0.14em',
  margin: '0 0 6px',
}

const tagline: React.CSSProperties = {
  color: ACCENT,
  fontSize: '10px',
  letterSpacing: '0.22em',
  margin: 0,
  fontFamily: 'monospace',
}

const introSection: React.CSSProperties = {
  padding: '32px 40px 24px',
}

const greetingText: React.CSSProperties = {
  color: INK,
  fontSize: '16px',
  fontWeight: 600,
  margin: '0 0 12px',
}

const introText: React.CSSProperties = {
  color: 'rgba(20,20,19,0.78)',
  fontSize: '15px',
  lineHeight: '1.65',
  margin: '0 0 12px',
}

const highlight: React.CSSProperties = {
  color: INK,
}

const metaText: React.CSSProperties = {
  color: 'rgba(20,20,19,0.45)',
  fontSize: '11px',
  fontFamily: 'monospace',
  letterSpacing: '0.1em',
  margin: '8px 0 0',
}

const divider: React.CSSProperties = {
  borderColor: RULE,
  margin: '0',
}

const reportSection: React.CSSProperties = {
  padding: '24px 40px',
  borderBottom: `1px solid ${RULE}`,
}

const sectionHeading: React.CSSProperties = {
  color: ACCENT,
  fontSize: '10px',
  fontWeight: 700,
  letterSpacing: '0.18em',
  textTransform: 'uppercase',
  margin: '0 0 14px',
  fontFamily: 'monospace',
}

const bodyText: React.CSSProperties = {
  color: 'rgba(20,20,19,0.82)',
  fontSize: '14px',
  lineHeight: '1.65',
  margin: '0 0 8px',
}

const boldLine: React.CSSProperties = {
  color: INK,
  fontSize: '14px',
  fontWeight: 600,
  lineHeight: '1.6',
  margin: '0 0 6px',
}

const bulletLine: React.CSSProperties = {
  color: 'rgba(20,20,19,0.82)',
  fontSize: '14px',
  lineHeight: '1.6',
  margin: '0 0 4px',
  paddingLeft: '4px',
}

const ctaSection: React.CSSProperties = {
  padding: '36px 40px',
  textAlign: 'center',
  backgroundColor: 'rgba(20,20,19,0.02)',
}

const ctaHeading: React.CSSProperties = {
  color: INK,
  fontSize: '20px',
  fontWeight: 600,
  margin: '0 0 12px',
  letterSpacing: '-0.01em',
}

const ctaText: React.CSSProperties = {
  color: 'rgba(20,20,19,0.65)',
  fontSize: '14px',
  lineHeight: '1.6',
  margin: '0 0 24px',
}

const ctaButton: React.CSSProperties = {
  backgroundColor: INK,
  color: PAPER,
  fontSize: '12px',
  fontWeight: 600,
  letterSpacing: '0.08em',
  padding: '14px 28px',
  textDecoration: 'none',
  display: 'inline-block',
}

const footerSection: React.CSSProperties = {
  padding: '24px 40px',
  textAlign: 'center',
}

const footerText: React.CSSProperties = {
  color: 'rgba(20,20,19,0.45)',
  fontSize: '12px',
  margin: '0 0 6px',
}

const footerLink: React.CSSProperties = {
  color: 'rgba(20,20,19,0.45)',
  textDecoration: 'underline',
}

const footerSmall: React.CSSProperties = {
  color: 'rgba(20,20,19,0.3)',
  fontSize: '11px',
  lineHeight: '1.5',
  margin: 0,
}
